// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: event.proto

package eventpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	commonpb "github.com/milvus-io/milvus/pkg/v2/proto/commonpb"
)

// EventType 定义事件类型
type EventType int32

const (
	EVENT_UNKNOWN            EventType = 0
	USER_MESSAGE             EventType = 1
	ASSISTANT_MESSAGE        EventType = 2
	TOOL_CALL_ISSUED         EventType = 10
	TOOL_RESULT_RETURNED     EventType = 11
	RETRIEVAL_EXECUTED       EventType = 20
	MEMORY_WRITE_REQUESTED   EventType = 30
	MEMORY_CONSOLIDATED      EventType = 31
	MEMORY_UPDATED           EventType = 32
	MEMORY_DELETED           EventType = 33
	PLAN_UPDATED             EventType = 40
	PLAN_EXECUTED            EventType = 41
	CRITIQUE_GENERATED       EventType = 50
	REFLECTION_CREATED       EventType = 51
	TASK_STARTED             EventType = 60
	TASK_FINISHED            EventType = 61
	TASK_FAILED              EventType = 62
	HANDOFF_OCCURRED         EventType = 70
	SHARED_MEMORY_ACCESSED   EventType = 71
	SESSION_CREATED          EventType = 80
	SESSION_ENDED            EventType = 81
	AGENT_REGISTERED         EventType = 82
	AGENT_DEREGISTERED       EventType = 83
)

var EventType_name = map[int32]string{
	0:  "EVENT_UNKNOWN",
	1:  "USER_MESSAGE",
	2:  "ASSISTANT_MESSAGE",
	10: "TOOL_CALL_ISSUED",
	11: "TOOL_RESULT_RETURNED",
	20: "RETRIEVAL_EXECUTED",
	30: "MEMORY_WRITE_REQUESTED",
	31: "MEMORY_CONSOLIDATED",
	32: "MEMORY_UPDATED",
	33: "MEMORY_DELETED",
	40: "PLAN_UPDATED",
	41: "PLAN_EXECUTED",
	50: "CRITIQUE_GENERATED",
	51: "REFLECTION_CREATED",
	60: "TASK_STARTED",
	61: "TASK_FINISHED",
	62: "TASK_FAILED",
	70: "HANDOFF_OCCURRED",
	71: "SHARED_MEMORY_ACCESSED",
	80: "SESSION_CREATED",
	81: "SESSION_ENDED",
	82: "AGENT_REGISTERED",
	83: "AGENT_DEREGISTERED",
}

var EventType_value = map[string]int32{
	"EVENT_UNKNOWN":          0,
	"USER_MESSAGE":           1,
	"ASSISTANT_MESSAGE":      2,
	"TOOL_CALL_ISSUED":       10,
	"TOOL_RESULT_RETURNED":   11,
	"RETRIEVAL_EXECUTED":     20,
	"MEMORY_WRITE_REQUESTED": 30,
	"MEMORY_CONSOLIDATED":    31,
	"MEMORY_UPDATED":         32,
	"MEMORY_DELETED":         33,
	"PLAN_UPDATED":           40,
	"PLAN_EXECUTED":          41,
	"CRITIQUE_GENERATED":     50,
	"REFLECTION_CREATED":     51,
	"TASK_STARTED":           60,
	"TASK_FINISHED":          61,
	"TASK_FAILED":            62,
	"HANDOFF_OCCURRED":       70,
	"SHARED_MEMORY_ACCESSED": 71,
	"SESSION_CREATED":        80,
	"SESSION_ENDED":          81,
	"AGENT_REGISTERED":       82,
	"AGENT_DEREGISTERED":     83,
}

func (x EventType) String() string {
	return EventType_name[int32(x)]
}

// Event 系统事实来源
type Event struct {
	EventId       string            `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId      string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string            `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentId       string            `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string            `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     EventType         `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=event.proto.EventType" json:"event_type,omitempty"`
	EventTime     uint64            `protobuf:"varint,7,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	IngestTime    uint64            `protobuf:"varint,8,opt,name=ingest_time,json=ingestTime,proto3" json:"ingest_time,omitempty"`
	VisibleTime   uint64            `protobuf:"varint,9,opt,name=visible_time,json=visibleTime,proto3" json:"visible_time,omitempty"`
	LogicalTs     uint64            `protobuf:"varint,10,opt,name=logical_ts,json=logicalTs,proto3" json:"logical_ts,omitempty"`
	ParentEventId string            `protobuf:"bytes,11,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	CausalRefs    []string          `protobuf:"bytes,12,rep,name=causal_refs,json=causalRefs,proto3" json:"causal_refs,omitempty"`
	Payload       []byte            `protobuf:"bytes,13,opt,name=payload,proto3" json:"payload,omitempty"`
	Source        string            `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	Importance    float32           `protobuf:"fixed32,15,opt,name=importance,proto3" json:"importance,omitempty"`
	Visibility    string            `protobuf:"bytes,16,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Version       int64             `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,18,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Event) Reset() {
	*x = Event{}
}

func (x *Event) String() string {
	return "Event"
}

func (*Event) ProtoMessage() {}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Event) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EVENT_UNKNOWN
}

func (x *Event) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *Event) GetIngestTime() uint64 {
	if x != nil {
		return x.IngestTime
	}
	return 0
}

func (x *Event) GetVisibleTime() uint64 {
	if x != nil {
		return x.VisibleTime
	}
	return 0
}

func (x *Event) GetLogicalTs() uint64 {
	if x != nil {
		return x.LogicalTs
	}
	return 0
}

func (x *Event) GetParentEventId() string {
	if x != nil {
		return x.ParentEventId
	}
	return ""
}

func (x *Event) GetCausalRefs() []string {
	if x != nil {
		return x.CausalRefs
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event