// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: event.proto

package eventpb

import (
	commonpb "github.com/milvus-io/milvus/pkg/v2/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType 定义事件类型
type EventType int32

const (
	EventType_EVENT_UNKNOWN EventType = 0
	// 消息类事件
	EventType_USER_MESSAGE      EventType = 1
	EventType_ASSISTANT_MESSAGE EventType = 2
	// 工具类事件
	EventType_TOOL_CALL_ISSUED     EventType = 10
	EventType_TOOL_RESULT_RETURNED EventType = 11
	// 检索类事件
	EventType_RETRIEVAL_EXECUTED EventType = 20
	// 记忆类事件
	EventType_MEMORY_WRITE_REQUESTED EventType = 30
	EventType_MEMORY_CONSOLIDATED    EventType = 31
	EventType_MEMORY_UPDATED         EventType = 32
	EventType_MEMORY_DELETED         EventType = 33
	// 计划类事件
	EventType_PLAN_UPDATED  EventType = 40
	EventType_PLAN_EXECUTED EventType = 41
	// 反思类事件
	EventType_CRITIQUE_GENERATED EventType = 50
	EventType_REFLECTION_CREATED EventType = 51
	// 任务类事件
	EventType_TASK_STARTED  EventType = 60
	EventType_TASK_FINISHED EventType = 61
	EventType_TASK_FAILED   EventType = 62
	// 协作类事件
	EventType_HANDOFF_OCCURRED       EventType = 70
	EventType_SHARED_MEMORY_ACCESSED EventType = 71
	// 系统类事件
	EventType_SESSION_CREATED    EventType = 80
	EventType_SESSION_ENDED      EventType = 81
	EventType_AGENT_REGISTERED   EventType = 82
	EventType_AGENT_DEREGISTERED EventType = 83
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_UNKNOWN",
		1:  "USER_MESSAGE",
		2:  "ASSISTANT_MESSAGE",
		10: "TOOL_CALL_ISSUED",
		11: "TOOL_RESULT_RETURNED",
		20: "RETRIEVAL_EXECUTED",
		30: "MEMORY_WRITE_REQUESTED",
		31: "MEMORY_CONSOLIDATED",
		32: "MEMORY_UPDATED",
		33: "MEMORY_DELETED",
		40: "PLAN_UPDATED",
		41: "PLAN_EXECUTED",
		50: "CRITIQUE_GENERATED",
		51: "REFLECTION_CREATED",
		60: "TASK_STARTED",
		61: "TASK_FINISHED",
		62: "TASK_FAILED",
		70: "HANDOFF_OCCURRED",
		71: "SHARED_MEMORY_ACCESSED",
		80: "SESSION_CREATED",
		81: "SESSION_ENDED",
		82: "AGENT_REGISTERED",
		83: "AGENT_DEREGISTERED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNKNOWN":          0,
		"USER_MESSAGE":           1,
		"ASSISTANT_MESSAGE":      2,
		"TOOL_CALL_ISSUED":       10,
		"TOOL_RESULT_RETURNED":   11,
		"RETRIEVAL_EXECUTED":     20,
		"MEMORY_WRITE_REQUESTED": 30,
		"MEMORY_CONSOLIDATED":    31,
		"MEMORY_UPDATED":         32,
		"MEMORY_DELETED":         33,
		"PLAN_UPDATED":           40,
		"PLAN_EXECUTED":          41,
		"CRITIQUE_GENERATED":     50,
		"REFLECTION_CREATED":     51,
		"TASK_STARTED":           60,
		"TASK_FINISHED":          61,
		"TASK_FAILED":            62,
		"HANDOFF_OCCURRED":       70,
		"SHARED_MEMORY_ACCESSED": 71,
		"SESSION_CREATED":        80,
		"SESSION_ENDED":          81,
		"AGENT_REGISTERED":       82,
		"AGENT_DEREGISTERED":     83,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// Event 系统事实来源
type Event struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId    string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentId     string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId   string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType   EventType              `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=event.proto.EventType" json:"event_type,omitempty"`
	// 时间戳
	EventTime   uint64 `protobuf:"varint,7,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`       // 事件实际发生时间
	IngestTime  uint64 `protobuf:"varint,8,opt,name=ingest_time,json=ingestTime,proto3" json:"ingest_time,omitempty"`    // 进入WAL时间
	VisibleTime uint64 `protobuf:"varint,9,opt,name=visible_time,json=visibleTime,proto3" json:"visible_time,omitempty"` // 对查询可见时间
	LogicalTs   uint64 `protobuf:"varint,10,opt,name=logical_ts,json=logicalTs,proto3" json:"logical_ts,omitempty"`      // 逻辑时间戳
	// 因果关系
	ParentEventId string   `protobuf:"bytes,11,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	CausalRefs    []string `protobuf:"bytes,12,rep,name=causal_refs,json=causalRefs,proto3" json:"causal_refs,omitempty"`
	// 内容
	Payload []byte `protobuf:"bytes,13,opt,name=payload,proto3" json:"payload,omitempty"`
	Source  string `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	// 重要性
	Importance float32 `protobuf:"fixed32,15,opt,name=importance,proto3" json:"importance,omitempty"`
	// 可见性
	Visibility string `protobuf:"bytes,16,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// 版本
	Version int64 `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	// 元数据
	Metadata      map[string]string `protobuf:"bytes,18,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Event) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_UNKNOWN
}

func (x *Event) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *Event) GetIngestTime() uint64 {
	if x != nil {
		return x.IngestTime
	}
	return 0
}

func (x *Event) GetVisibleTime() uint64 {
	if x != nil {
		return x.VisibleTime
	}
	return 0
}

func (x *Event) GetLogicalTs() uint64 {
	if x != nil {
		return x.LogicalTs
	}
	return 0
}

func (x *Event) GetParentEventId() string {
	if x != nil {
		return x.ParentEventId
	}
	return ""
}

func (x *Event) GetCausalRefs() []string {
	if x != nil {
		return x.CausalRefs
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Event) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EventBatch 事件批次
type EventBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Events         []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	BatchTimestamp uint64                 `protobuf:"varint,2,opt,name=batch_timestamp,json=batchTimestamp,proto3" json:"batch_timestamp,omitempty"`
	BatchId        string                 `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetBatchTimestamp() uint64 {
	if x != nil {
		return x.BatchTimestamp
	}
	return 0
}

func (x *EventBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

// EventFilter 事件过滤条件
type EventFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentIds       []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	SessionIds     []string               `protobuf:"bytes,2,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	EventTypes     []EventType            `protobuf:"varint,3,rep,packed,name=event_types,json=eventTypes,proto3,enum=event.proto.EventType" json:"event_types,omitempty"`
	StartTime      uint64                 `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        uint64                 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinImportance  float32                `protobuf:"fixed32,6,opt,name=min_importance,json=minImportance,proto3" json:"min_importance,omitempty"`
	MaxImportance  float32                `protobuf:"fixed32,7,opt,name=max_importance,json=maxImportance,proto3" json:"max_importance,omitempty"`
	MetadataFilter map[string]string      `protobuf:"bytes,8,rep,name=metadata_filter,json=metadataFilter,proto3" json:"metadata_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventFilter) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *EventFilter) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *EventFilter) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *EventFilter) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *EventFilter) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *EventFilter) GetMinImportance() float32 {
	if x != nil {
		return x.MinImportance
	}
	return 0
}

func (x *EventFilter) GetMaxImportance() float32 {
	if x != nil {
		return x.MaxImportance
	}
	return 0
}

func (x *EventFilter) GetMetadataFilter() map[string]string {
	if x != nil {
		return x.MetadataFilter
	}
	return nil
}

// AppendEventRequest 追加事件请求
type AppendEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     EventType              `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=event.proto.EventType" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Importance    float32                `protobuf:"fixed32,7,opt,name=importance,proto3" json:"importance,omitempty"`
	Visibility    string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	ParentEventId string                 `protobuf:"bytes,9,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	CausalRefs    []string               `protobuf:"bytes,10,rep,name=causal_refs,json=causalRefs,proto3" json:"causal_refs,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventRequest) Reset() {
	*x = AppendEventRequest{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventRequest) ProtoMessage() {}

func (x *AppendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventRequest.ProtoReflect.Descriptor instead.
func (*AppendEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEventRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AppendEventRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AppendEventRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AppendEventRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AppendEventRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_UNKNOWN
}

func (x *AppendEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendEventRequest) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *AppendEventRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *AppendEventRequest) GetParentEventId() string {
	if x != nil {
		return x.ParentEventId
	}
	return ""
}

func (x *AppendEventRequest) GetCausalRefs() []string {
	if x != nil {
		return x.CausalRefs
	}
	return nil
}

func (x *AppendEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AppendEventResponse 追加事件响应
type AppendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	LogicalTs     uint64                 `protobuf:"varint,3,opt,name=logical_ts,json=logicalTs,proto3" json:"logical_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventResponse) Reset() {
	*x = AppendEventResponse{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventResponse) ProtoMessage() {}

func (x *AppendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventResponse.ProtoReflect.Descriptor instead.
func (*AppendEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEventResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AppendEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AppendEventResponse) GetLogicalTs() uint64 {
	if x != nil {
		return x.LogicalTs
	}
	return 0
}

// GetEventRequest 获取事件请求
type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// GetEventResponse 获取事件响应
type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// QueryEventsRequest 查询事件请求
type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *EventFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // "time", "importance", "logical_ts"
	Ascending     bool                   `protobuf:"varint,5,opt,name=ascending,proto3" json:"ascending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *QueryEventsRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryEventsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryEventsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *QueryEventsRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

// QueryEventsResponse 查询事件响应
type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *QueryEventsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryEventsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// SubscribeEventsRequest 订阅事件请求
type SubscribeEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId   string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Filter         *EventFilter           `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	StartTimestamp uint64                 `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeEventsRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeEventsRequest) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SubscribeEventsRequest) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

// SubscribeEventsResponse 订阅事件响应（流式）
type SubscribeEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SubscribeEventsResponse_Event
	//	*SubscribeEventsResponse_Status
	Response      isSubscribeEventsResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsResponse) Reset() {
	*x = SubscribeEventsResponse{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsResponse) ProtoMessage() {}

func (x *SubscribeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeEventsResponse) GetResponse() isSubscribeEventsResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SubscribeEventsResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Response.(*SubscribeEventsResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *SubscribeEventsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		if x, ok := x.Response.(*SubscribeEventsResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isSubscribeEventsResponse_Response interface {
	isSubscribeEventsResponse_Response()
}

type SubscribeEventsResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type SubscribeEventsResponse_Status struct {
	Status *commonpb.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*SubscribeEventsResponse_Event) isSubscribeEventsResponse_Response() {}

func (*SubscribeEventsResponse_Status) isSubscribeEventsResponse_Response() {}

// EventLogPosition 事件日志位置
type EventLogPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelName   string                 `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	LogId         uint64                 `protobuf:"varint,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLogPosition) Reset() {
	*x = EventLogPosition{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLogPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLogPosition) ProtoMessage() {}

func (x *EventLogPosition) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLogPosition.ProtoReflect.Descriptor instead.
func (*EventLogPosition) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *EventLogPosition) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *EventLogPosition) GetLogId() uint64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *EventLogPosition) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\vevent.proto\x1a\fcommon.proto\"\xa5\x05\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x125\n" +
	"\n" +
	"event_type\x18\x06 \x01(\x0e2\x16.event.proto.EventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"event_time\x18\a \x01(\x04R\teventTime\x12\x1f\n" +
	"\vingest_time\x18\b \x01(\x04R\n" +
	"ingestTime\x12!\n" +
	"\fvisible_time\x18\t \x01(\x04R\vvisibleTime\x12\x1d\n" +
	"\n" +
	"logical_ts\x18\n" +
	" \x01(\x04R\tlogicalTs\x12&\n" +
	"\x0fparent_event_id\x18\v \x01(\tR\rparentEventId\x12\x1f\n" +
	"\vcausal_refs\x18\f \x03(\tR\n" +
	"causalRefs\x12\x18\n" +
	"\apayload\x18\r \x01(\fR\apayload\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"importance\x18\x0f \x01(\x02R\n" +
	"importance\x12\x1e\n" +
	"\n" +
	"visibility\x18\x10 \x01(\tR\n" +
	"visibility\x12\x18\n" +
	"\aversion\x18\x11 \x01(\x03R\aversion\x12<\n" +
	"\bmetadata\x18\x12 \x03(\v2 .event.proto.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\n" +
	"EventBatch\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.event.proto.EventR\x06events\x12'\n" +
	"\x0fbatch_timestamp\x18\x02 \x01(\x04R\x0ebatchTimestamp\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\tR\abatchId\"\xa6\x03\n" +
	"\vEventFilter\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\x12\x1f\n" +
	"\vsession_ids\x18\x02 \x03(\tR\n" +
	"sessionIds\x127\n" +
	"\vevent_types\x18\x03 \x03(\x0e2\x16.event.proto.EventTypeR\n" +
	"eventTypes\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x04R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x04R\aendTime\x12%\n" +
	"\x0emin_importance\x18\x06 \x01(\x02R\rminImportance\x12%\n" +
	"\x0emax_importance\x18\a \x01(\x02R\rmaxImportance\x12U\n" +
	"\x0fmetadata_filter\x18\b \x03(\v2,.event.proto.EventFilter.MetadataFilterEntryR\x0emetadataFilter\x1aA\n" +
	"\x13MetadataFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x03\n" +
	"\x12AppendEventRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x125\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x16.event.proto.EventTypeR\teventType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1e\n" +
	"\n" +
	"importance\x18\a \x01(\x02R\n" +
	"importance\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibility\x12&\n" +
	"\x0fparent_event_id\x18\t \x01(\tR\rparentEventId\x12\x1f\n" +
	"\vcausal_refs\x18\n" +
	" \x03(\tR\n" +
	"causalRefs\x12I\n" +
	"\bmetadata\x18\v \x03(\v2-.event.proto.AppendEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x13AppendEventResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"logical_ts\x18\x03 \x01(\x04R\tlogicalTs\",\n" +
	"\x0fGetEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"j\n" +
	"\x10GetEventResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12(\n" +
	"\x05event\x18\x02 \x01(\v2\x12.event.proto.EventR\x05event\"\xad\x01\n" +
	"\x12QueryEventsRequest\x120\n" +
	"\x06filter\x18\x01 \x01(\v2\x18.event.proto.EventFilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12\x1c\n" +
	"\tascending\x18\x05 \x01(\bR\tascending\"\x90\x01\n" +
	"\x13QueryEventsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12*\n" +
	"\x06events\x18\x02 \x03(\v2\x12.event.proto.EventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\"\x98\x01\n" +
	"\x16SubscribeEventsRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x120\n" +
	"\x06filter\x18\x02 \x01(\v2\x18.event.proto.EventFilterR\x06filter\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x04R\x0estartTimestamp\"\x81\x01\n" +
	"\x17SubscribeEventsResponse\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x12.event.proto.EventH\x00R\x05event\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x14.common.proto.StatusH\x00R\x06statusB\n" +
	"\n" +
	"\bresponse\"j\n" +
	"\x10EventLogPosition\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\x04R\x05logId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp*\xff\x03\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x10\n" +
	"\fUSER_MESSAGE\x10\x01\x12\x15\n" +
	"\x11ASSISTANT_MESSAGE\x10\x02\x12\x14\n" +
	"\x10TOOL_CALL_ISSUED\x10\n" +
	"\x12\x18\n" +
	"\x14TOOL_RESULT_RETURNED\x10\v\x12\x16\n" +
	"\x12RETRIEVAL_EXECUTED\x10\x14\x12\x1a\n" +
	"\x16MEMORY_WRITE_REQUESTED\x10\x1e\x12\x17\n" +
	"\x13MEMORY_CONSOLIDATED\x10\x1f\x12\x12\n" +
	"\x0eMEMORY_UPDATED\x10 \x12\x12\n" +
	"\x0eMEMORY_DELETED\x10!\x12\x10\n" +
	"\fPLAN_UPDATED\x10(\x12\x11\n" +
	"\rPLAN_EXECUTED\x10)\x12\x16\n" +
	"\x12CRITIQUE_GENERATED\x102\x12\x16\n" +
	"\x12REFLECTION_CREATED\x103\x12\x10\n" +
	"\fTASK_STARTED\x10<\x12\x11\n" +
	"\rTASK_FINISHED\x10=\x12\x0f\n" +
	"\vTASK_FAILED\x10>\x12\x14\n" +
	"\x10HANDOFF_OCCURRED\x10F\x12\x1a\n" +
	"\x16SHARED_MEMORY_ACCESSED\x10G\x12\x13\n" +
	"\x0fSESSION_CREATED\x10P\x12\x11\n" +
	"\rSESSION_ENDED\x10Q\x12\x14\n" +
	"\x10AGENT_REGISTERED\x10R\x12\x16\n" +
	"\x12AGENT_DEREGISTERED\x10S2\xdb\x02\n" +
	"\fEventService\x12P\n" +
	"\vAppendEvent\x12\x1f.event.proto.AppendEventRequest\x1a .event.proto.AppendEventResponse\x12G\n" +
	"\bGetEvent\x12\x1c.event.proto.GetEventRequest\x1a\x1d.event.proto.GetEventResponse\x12P\n" +
	"\vQueryEvents\x12\x1f.event.proto.QueryEventsRequest\x1a .event.proto.QueryEventsResponse\x12^\n" +
	"\x0fSubscribeEvents\x12#.event.proto.SubscribeEventsRequest\x1a$.event.proto.SubscribeEventsResponse0\x01B2Z0github.com/milvus-io/milvus/pkg/v2/proto/eventpbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_event_proto_goTypes = []any{
	(EventType)(0),                  // 0: event.proto.EventType
	(*Event)(nil),                   // 1: event.proto.Event
	(*EventBatch)(nil),              // 2: event.proto.EventBatch
	(*EventFilter)(nil),             // 3: event.proto.EventFilter
	(*AppendEventRequest)(nil),      // 4: event.proto.AppendEventRequest
	(*AppendEventResponse)(nil),     // 5: event.proto.AppendEventResponse
	(*GetEventRequest)(nil),         // 6: event.proto.GetEventRequest
	(*GetEventResponse)(nil),        // 7: event.proto.GetEventResponse
	(*QueryEventsRequest)(nil),      // 8: event.proto.QueryEventsRequest
	(*QueryEventsResponse)(nil),     // 9: event.proto.QueryEventsResponse
	(*SubscribeEventsRequest)(nil),  // 10: event.proto.SubscribeEventsRequest
	(*SubscribeEventsResponse)(nil), // 11: event.proto.SubscribeEventsResponse
	(*EventLogPosition)(nil),        // 12: event.proto.EventLogPosition
	nil,                             // 13: event.proto.Event.MetadataEntry
	nil,                             // 14: event.proto.EventFilter.MetadataFilterEntry
	nil,                             // 15: event.proto.AppendEventRequest.MetadataEntry
	(*commonpb.Status)(nil),         // 16: common.proto.Status
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: event.proto.Event.event_type:type_name -> event.proto.EventType
	13, // 1: event.proto.Event.metadata:type_name -> event.proto.Event.MetadataEntry
	1,  // 2: event.proto.EventBatch.events:type_name -> event.proto.Event
	0,  // 3: event.proto.EventFilter.event_types:type_name -> event.proto.EventType
	14, // 4: event.proto.EventFilter.metadata_filter:type_name -> event.proto.EventFilter.MetadataFilterEntry
	0,  // 5: event.proto.AppendEventRequest.event_type:type_name -> event.proto.EventType
	15, // 6: event.proto.AppendEventRequest.metadata:type_name -> event.proto.AppendEventRequest.MetadataEntry
	16, // 7: event.proto.AppendEventResponse.status:type_name -> common.proto.Status
	16, // 8: event.proto.GetEventResponse.status:type_name -> common.proto.Status
	1,  // 9: event.proto.GetEventResponse.event:type_name -> event.proto.Event
	3,  // 10: event.proto.QueryEventsRequest.filter:type_name -> event.proto.EventFilter
	16, // 11: event.proto.QueryEventsResponse.status:type_name -> common.proto.Status
	1,  // 12: event.proto.QueryEventsResponse.events:type_name -> event.proto.Event
	3,  // 13: event.proto.SubscribeEventsRequest.filter:type_name -> event.proto.EventFilter
	1,  // 14: event.proto.SubscribeEventsResponse.event:type_name -> event.proto.Event
	16, // 15: event.proto.SubscribeEventsResponse.status:type_name -> common.proto.Status
	4,  // 16: event.proto.EventService.AppendEvent:input_type -> event.proto.AppendEventRequest
	6,  // 17: event.proto.EventService.GetEvent:input_type -> event.proto.GetEventRequest
	8,  // 18: event.proto.EventService.QueryEvents:input_type -> event.proto.QueryEventsRequest
	10, // 19: event.proto.EventService.SubscribeEvents:input_type -> event.proto.SubscribeEventsRequest
	5,  // 20: event.proto.EventService.AppendEvent:output_type -> event.proto.AppendEventResponse
	7,  // 21: event.proto.EventService.GetEvent:output_type -> event.proto.GetEventResponse
	9,  // 22: event.proto.EventService.QueryEvents:output_type -> event.proto.QueryEventsResponse
	11, // 23: event.proto.EventService.SubscribeEvents:output_type -> event.proto.SubscribeEventsResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[10].OneofWrappers = []any{
		(*SubscribeEventsResponse_Event)(nil),
		(*SubscribeEventsResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
