// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode 错误码
type ErrorCode int32

const (
	ErrorCode_Success                       ErrorCode = 0
	ErrorCode_UnexpectedError               ErrorCode = 1
	ErrorCode_ConnectFailed                 ErrorCode = 2
	ErrorCode_PermissionDenied              ErrorCode = 3
	ErrorCode_CollectionNotFound            ErrorCode = 4
	ErrorCode_IllegalArgument               ErrorCode = 5
	ErrorCode_IllegalDimension              ErrorCode = 7
	ErrorCode_IllegalIndexType              ErrorCode = 8
	ErrorCode_IllegalCollectionName         ErrorCode = 9
	ErrorCode_IllegalTOPK                   ErrorCode = 10
	ErrorCode_IllegalRowRecord              ErrorCode = 11
	ErrorCode_IllegalVectorID               ErrorCode = 12
	ErrorCode_IllegalSearchResult           ErrorCode = 13
	ErrorCode_FileNotFound                  ErrorCode = 14
	ErrorCode_MetaFailed                    ErrorCode = 15
	ErrorCode_CacheFailed                   ErrorCode = 16
	ErrorCode_CannotCreateFolder            ErrorCode = 17
	ErrorCode_CannotCreateFile              ErrorCode = 18
	ErrorCode_CannotDeleteFolder            ErrorCode = 19
	ErrorCode_CannotDeleteFile              ErrorCode = 20
	ErrorCode_BuildIndexError               ErrorCode = 21
	ErrorCode_IllegalNLIST                  ErrorCode = 22
	ErrorCode_IllegalMetricType             ErrorCode = 23
	ErrorCode_OutOfMemory                   ErrorCode = 24
	ErrorCode_IndexNotExist                 ErrorCode = 25
	ErrorCode_EmptyCollection               ErrorCode = 26
	ErrorCode_UpdateImportTaskFailure       ErrorCode = 27
	ErrorCode_CollectionNameNotFound        ErrorCode = 28
	ErrorCode_CreateCredentialFailure       ErrorCode = 29
	ErrorCode_UpdateCredentialFailure       ErrorCode = 30
	ErrorCode_DeleteCredentialFailure       ErrorCode = 31
	ErrorCode_GetCredentialFailure          ErrorCode = 32
	ErrorCode_ListCredUsersFailure          ErrorCode = 33
	ErrorCode_GetUserFailure                ErrorCode = 34
	ErrorCode_CreateRoleFailure             ErrorCode = 35
	ErrorCode_DropRoleFailure               ErrorCode = 36
	ErrorCode_OperateUserRoleFailure        ErrorCode = 37
	ErrorCode_SelectRoleFailure             ErrorCode = 38
	ErrorCode_SelectUserFailure             ErrorCode = 39
	ErrorCode_SelectResourceFailure         ErrorCode = 40
	ErrorCode_OperatePrivilegeFailure       ErrorCode = 41
	ErrorCode_SelectGrantFailure            ErrorCode = 42
	ErrorCode_RefreshPolicyInfoCacheFailure ErrorCode = 43
	ErrorCode_ListPolicyFailure             ErrorCode = 44
	ErrorCode_NotShardLeader                ErrorCode = 45
	ErrorCode_NoReplicaAvailable            ErrorCode = 46
	ErrorCode_SegmentNotFound               ErrorCode = 47
	ErrorCode_ForceDeny                     ErrorCode = 48
	ErrorCode_RateLimit                     ErrorCode = 49
	ErrorCode_NodeIDNotMatch                ErrorCode = 50
	ErrorCode_UpsertAutoIDTrue              ErrorCode = 51
	ErrorCode_InsufficientMemoryToLoad      ErrorCode = 52
	ErrorCode_MemoryQuotaExhausted          ErrorCode = 53
	ErrorCode_DiskQuotaExhausted            ErrorCode = 54
	ErrorCode_TimeTickLongDelay             ErrorCode = 55
	ErrorCode_NotFoundTSafer                ErrorCode = 56
	ErrorCode_DenyToRewrite                 ErrorCode = 57
	ErrorCode_InvalidPassword               ErrorCode = 58
	ErrorCode_DDRequestRace                 ErrorCode = 59
	// internal error code for DC
	ErrorCode_DCNotReady ErrorCode = 100
	// internal error code for DN
	ErrorCode_DNNotReady ErrorCode = 101
	// internal error code for CGO
	ErrorCode_CGOError ErrorCode = 102
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "Success",
		1:   "UnexpectedError",
		2:   "ConnectFailed",
		3:   "PermissionDenied",
		4:   "CollectionNotFound",
		5:   "IllegalArgument",
		7:   "IllegalDimension",
		8:   "IllegalIndexType",
		9:   "IllegalCollectionName",
		10:  "IllegalTOPK",
		11:  "IllegalRowRecord",
		12:  "IllegalVectorID",
		13:  "IllegalSearchResult",
		14:  "FileNotFound",
		15:  "MetaFailed",
		16:  "CacheFailed",
		17:  "CannotCreateFolder",
		18:  "CannotCreateFile",
		19:  "CannotDeleteFolder",
		20:  "CannotDeleteFile",
		21:  "BuildIndexError",
		22:  "IllegalNLIST",
		23:  "IllegalMetricType",
		24:  "OutOfMemory",
		25:  "IndexNotExist",
		26:  "EmptyCollection",
		27:  "UpdateImportTaskFailure",
		28:  "CollectionNameNotFound",
		29:  "CreateCredentialFailure",
		30:  "UpdateCredentialFailure",
		31:  "DeleteCredentialFailure",
		32:  "GetCredentialFailure",
		33:  "ListCredUsersFailure",
		34:  "GetUserFailure",
		35:  "CreateRoleFailure",
		36:  "DropRoleFailure",
		37:  "OperateUserRoleFailure",
		38:  "SelectRoleFailure",
		39:  "SelectUserFailure",
		40:  "SelectResourceFailure",
		41:  "OperatePrivilegeFailure",
		42:  "SelectGrantFailure",
		43:  "RefreshPolicyInfoCacheFailure",
		44:  "ListPolicyFailure",
		45:  "NotShardLeader",
		46:  "NoReplicaAvailable",
		47:  "SegmentNotFound",
		48:  "ForceDeny",
		49:  "RateLimit",
		50:  "NodeIDNotMatch",
		51:  "UpsertAutoIDTrue",
		52:  "InsufficientMemoryToLoad",
		53:  "MemoryQuotaExhausted",
		54:  "DiskQuotaExhausted",
		55:  "TimeTickLongDelay",
		56:  "NotFoundTSafer",
		57:  "DenyToRewrite",
		58:  "InvalidPassword",
		59:  "DDRequestRace",
		100: "DCNotReady",
		101: "DNNotReady",
		102: "CGOError",
	}
	ErrorCode_value = map[string]int32{
		"Success":                       0,
		"UnexpectedError":               1,
		"ConnectFailed":                 2,
		"PermissionDenied":              3,
		"CollectionNotFound":            4,
		"IllegalArgument":               5,
		"IllegalDimension":              7,
		"IllegalIndexType":              8,
		"IllegalCollectionName":         9,
		"IllegalTOPK":                   10,
		"IllegalRowRecord":              11,
		"IllegalVectorID":               12,
		"IllegalSearchResult":           13,
		"FileNotFound":                  14,
		"MetaFailed":                    15,
		"CacheFailed":                   16,
		"CannotCreateFolder":            17,
		"CannotCreateFile":              18,
		"CannotDeleteFolder":            19,
		"CannotDeleteFile":              20,
		"BuildIndexError":               21,
		"IllegalNLIST":                  22,
		"IllegalMetricType":             23,
		"OutOfMemory":                   24,
		"IndexNotExist":                 25,
		"EmptyCollection":               26,
		"UpdateImportTaskFailure":       27,
		"CollectionNameNotFound":        28,
		"CreateCredentialFailure":       29,
		"UpdateCredentialFailure":       30,
		"DeleteCredentialFailure":       31,
		"GetCredentialFailure":          32,
		"ListCredUsersFailure":          33,
		"GetUserFailure":                34,
		"CreateRoleFailure":             35,
		"DropRoleFailure":               36,
		"OperateUserRoleFailure":        37,
		"SelectRoleFailure":             38,
		"SelectUserFailure":             39,
		"SelectResourceFailure":         40,
		"OperatePrivilegeFailure":       41,
		"SelectGrantFailure":            42,
		"RefreshPolicyInfoCacheFailure": 43,
		"ListPolicyFailure":             44,
		"NotShardLeader":                45,
		"NoReplicaAvailable":            46,
		"SegmentNotFound":               47,
		"ForceDeny":                     48,
		"RateLimit":                     49,
		"NodeIDNotMatch":                50,
		"UpsertAutoIDTrue":              51,
		"InsufficientMemoryToLoad":      52,
		"MemoryQuotaExhausted":          53,
		"DiskQuotaExhausted":            54,
		"TimeTickLongDelay":             55,
		"NotFoundTSafer":                56,
		"DenyToRewrite":                 57,
		"InvalidPassword":               58,
		"DDRequestRace":                 59,
		"DCNotReady":                    100,
		"DNNotReady":                    101,
		"CGOError":                      102,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// ConsistencyLevel 一致性级别
type ConsistencyLevel int32

const (
	ConsistencyLevel_Strong     ConsistencyLevel = 0
	ConsistencyLevel_Session    ConsistencyLevel = 1
	ConsistencyLevel_Bounded    ConsistencyLevel = 2
	ConsistencyLevel_Eventually ConsistencyLevel = 3
	ConsistencyLevel_Customized ConsistencyLevel = 4
)

// Enum value maps for ConsistencyLevel.
var (
	ConsistencyLevel_name = map[int32]string{
		0: "Strong",
		1: "Session",
		2: "Bounded",
		3: "Eventually",
		4: "Customized",
	}
	ConsistencyLevel_value = map[string]int32{
		"Strong":     0,
		"Session":    1,
		"Bounded":    2,
		"Eventually": 3,
		"Customized": 4,
	}
)

func (x ConsistencyLevel) Enum() *ConsistencyLevel {
	p := new(ConsistencyLevel)
	*p = x
	return p
}

func (x ConsistencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ConsistencyLevel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ConsistencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyLevel.Descriptor instead.
func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// CompactionState 压缩状态
type CompactionState int32

const (
	CompactionState_UndefiedState CompactionState = 0
	CompactionState_Executing     CompactionState = 1
	CompactionState_Completed     CompactionState = 2
)

// Enum value maps for CompactionState.
var (
	CompactionState_name = map[int32]string{
		0: "UndefiedState",
		1: "Executing",
		2: "Completed",
	}
	CompactionState_value = map[string]int32{
		"UndefiedState": 0,
		"Executing":     1,
		"Completed":     2,
	}
)

func (x CompactionState) Enum() *CompactionState {
	p := new(CompactionState)
	*p = x
	return p
}

func (x CompactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (CompactionState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x CompactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompactionState.Descriptor instead.
func (CompactionState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// SegmentState Segment状态
type SegmentState int32

const (
	SegmentState_SegmentStateNone SegmentState = 0
	SegmentState_NotExist         SegmentState = 1
	SegmentState_Growing          SegmentState = 2
	SegmentState_Sealed           SegmentState = 3
	SegmentState_Flushed          SegmentState = 4
	SegmentState_Flushing         SegmentState = 5
	SegmentState_Dropped          SegmentState = 6
	SegmentState_Importing        SegmentState = 7
)

// Enum value maps for SegmentState.
var (
	SegmentState_name = map[int32]string{
		0: "SegmentStateNone",
		1: "NotExist",
		2: "Growing",
		3: "Sealed",
		4: "Flushed",
		5: "Flushing",
		6: "Dropped",
		7: "Importing",
	}
	SegmentState_value = map[string]int32{
		"SegmentStateNone": 0,
		"NotExist":         1,
		"Growing":          2,
		"Sealed":           3,
		"Flushed":          4,
		"Flushing":         5,
		"Dropped":          6,
		"Importing":        7,
	}
)

func (x SegmentState) Enum() *SegmentState {
	p := new(SegmentState)
	*p = x
	return p
}

func (x SegmentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (SegmentState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x SegmentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentState.Descriptor instead.
func (SegmentState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// ImportState 导入状态
type ImportState int32

const (
	ImportState_ImportPending          ImportState = 0
	ImportState_ImportFailed           ImportState = 1
	ImportState_ImportStarted          ImportState = 2
	ImportState_ImportPersisted        ImportState = 5
	ImportState_ImportCompleted        ImportState = 6
	ImportState_ImportFailedAndCleaned ImportState = 7
)

// Enum value maps for ImportState.
var (
	ImportState_name = map[int32]string{
		0: "ImportPending",
		1: "ImportFailed",
		2: "ImportStarted",
		5: "ImportPersisted",
		6: "ImportCompleted",
		7: "ImportFailedAndCleaned",
	}
	ImportState_value = map[string]int32{
		"ImportPending":          0,
		"ImportFailed":           1,
		"ImportStarted":          2,
		"ImportPersisted":        5,
		"ImportCompleted":        6,
		"ImportFailedAndCleaned": 7,
	}
)

func (x ImportState) Enum() *ImportState {
	p := new(ImportState)
	*p = x
	return p
}

func (x ImportState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (ImportState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x ImportState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportState.Descriptor instead.
func (ImportState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// ObjectType 对象类型
type ObjectType int32

const (
	ObjectType_Collection      ObjectType = 0
	ObjectType_Global          ObjectType = 1
	ObjectType_User            ObjectType = 2
	ObjectType_ObjectTypeCount ObjectType = 3
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "Collection",
		1: "Global",
		2: "User",
		3: "ObjectTypeCount",
	}
	ObjectType_value = map[string]int32{
		"Collection":      0,
		"Global":          1,
		"User":            2,
		"ObjectTypeCount": 3,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

// ObjectPrivilege 对象权限
type ObjectPrivilege int32

const (
	ObjectPrivilege_PrivilegeAll                ObjectPrivilege = 0
	ObjectPrivilege_PrivilegeCreate             ObjectPrivilege = 1
	ObjectPrivilege_PrivilegeDrop               ObjectPrivilege = 2
	ObjectPrivilege_PrivilegeAlter              ObjectPrivilege = 3
	ObjectPrivilege_PrivilegeRead               ObjectPrivilege = 4
	ObjectPrivilege_PrivilegeLoad               ObjectPrivilege = 5
	ObjectPrivilege_PrivilegeRelease            ObjectPrivilege = 6
	ObjectPrivilege_PrivilegeCompact            ObjectPrivilege = 7
	ObjectPrivilege_PrivilegeInsert             ObjectPrivilege = 8
	ObjectPrivilege_PrivilegeDelete             ObjectPrivilege = 9
	ObjectPrivilege_PrivilegeGetStatistics      ObjectPrivilege = 10
	ObjectPrivilege_PrivilegeCreateIndex        ObjectPrivilege = 11
	ObjectPrivilege_PrivilegeIndexDetail        ObjectPrivilege = 12
	ObjectPrivilege_PrivilegeDropIndex          ObjectPrivilege = 13
	ObjectPrivilege_PrivilegeSearch             ObjectPrivilege = 14
	ObjectPrivilege_PrivilegeFlush              ObjectPrivilege = 15
	ObjectPrivilege_PrivilegeQuery              ObjectPrivilege = 16
	ObjectPrivilege_PrivilegeLoadBalance        ObjectPrivilege = 17
	ObjectPrivilege_PrivilegeImport             ObjectPrivilege = 18
	ObjectPrivilege_PrivilegeBackup             ObjectPrivilege = 19
	ObjectPrivilege_PrivilegeRestore            ObjectPrivilege = 20
	ObjectPrivilege_PrivilegeListIndexes        ObjectPrivilege = 21
	ObjectPrivilege_PrivilegeCreateDatabase     ObjectPrivilege = 22
	ObjectPrivilege_PrivilegeDropDatabase       ObjectPrivilege = 23
	ObjectPrivilege_PrivilegeListDatabases      ObjectPrivilege = 24
	ObjectPrivilege_PrivilegeDescribeDatabase   ObjectPrivilege = 25
	ObjectPrivilege_PrivilegeAlterDatabase      ObjectPrivilege = 26
	ObjectPrivilege_PrivilegeDescribeCollection ObjectPrivilege = 27
	ObjectPrivilege_PrivilegeCount              ObjectPrivilege = 28
)

// Enum value maps for ObjectPrivilege.
var (
	ObjectPrivilege_name = map[int32]string{
		0:  "PrivilegeAll",
		1:  "PrivilegeCreate",
		2:  "PrivilegeDrop",
		3:  "PrivilegeAlter",
		4:  "PrivilegeRead",
		5:  "PrivilegeLoad",
		6:  "PrivilegeRelease",
		7:  "PrivilegeCompact",
		8:  "PrivilegeInsert",
		9:  "PrivilegeDelete",
		10: "PrivilegeGetStatistics",
		11: "PrivilegeCreateIndex",
		12: "PrivilegeIndexDetail",
		13: "PrivilegeDropIndex",
		14: "PrivilegeSearch",
		15: "PrivilegeFlush",
		16: "PrivilegeQuery",
		17: "PrivilegeLoadBalance",
		18: "PrivilegeImport",
		19: "PrivilegeBackup",
		20: "PrivilegeRestore",
		21: "PrivilegeListIndexes",
		22: "PrivilegeCreateDatabase",
		23: "PrivilegeDropDatabase",
		24: "PrivilegeListDatabases",
		25: "PrivilegeDescribeDatabase",
		26: "PrivilegeAlterDatabase",
		27: "PrivilegeDescribeCollection",
		28: "PrivilegeCount",
	}
	ObjectPrivilege_value = map[string]int32{
		"PrivilegeAll":                0,
		"PrivilegeCreate":             1,
		"PrivilegeDrop":               2,
		"PrivilegeAlter":              3,
		"PrivilegeRead":               4,
		"PrivilegeLoad":               5,
		"PrivilegeRelease":            6,
		"PrivilegeCompact":            7,
		"PrivilegeInsert":             8,
		"PrivilegeDelete":             9,
		"PrivilegeGetStatistics":      10,
		"PrivilegeCreateIndex":        11,
		"PrivilegeIndexDetail":        12,
		"PrivilegeDropIndex":          13,
		"PrivilegeSearch":             14,
		"PrivilegeFlush":              15,
		"PrivilegeQuery":              16,
		"PrivilegeLoadBalance":        17,
		"PrivilegeImport":             18,
		"PrivilegeBackup":             19,
		"PrivilegeRestore":            20,
		"PrivilegeListIndexes":        21,
		"PrivilegeCreateDatabase":     22,
		"PrivilegeDropDatabase":       23,
		"PrivilegeListDatabases":      24,
		"PrivilegeDescribeDatabase":   25,
		"PrivilegeAlterDatabase":      26,
		"PrivilegeDescribeCollection": 27,
		"PrivilegeCount":              28,
	}
)

func (x ObjectPrivilege) Enum() *ObjectPrivilege {
	p := new(ObjectPrivilege)
	*p = x
	return p
}

func (x ObjectPrivilege) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectPrivilege) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[6].Descriptor()
}

func (ObjectPrivilege) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[6]
}

func (x ObjectPrivilege) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectPrivilege.Descriptor instead.
func (ObjectPrivilege) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

// StateCode 状态码
type StateCode int32

const (
	StateCode_Initializing StateCode = 0
	StateCode_Healthy      StateCode = 1
	StateCode_Abnormal     StateCode = 2
	StateCode_StandBy      StateCode = 3
	StateCode_Stopping     StateCode = 4
)

// Enum value maps for StateCode.
var (
	StateCode_name = map[int32]string{
		0: "Initializing",
		1: "Healthy",
		2: "Abnormal",
		3: "StandBy",
		4: "Stopping",
	}
	StateCode_value = map[string]int32{
		"Initializing": 0,
		"Healthy":      1,
		"Abnormal":     2,
		"StandBy":      3,
		"Stopping":     4,
	}
)

func (x StateCode) Enum() *StateCode {
	p := new(StateCode)
	*p = x
	return p
}

func (x StateCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[7].Descriptor()
}

func (StateCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[7]
}

func (x StateCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateCode.Descriptor instead.
func (StateCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

// LoadState 加载状态
type LoadState int32

const (
	LoadState_LoadStateNotExist  LoadState = 0
	LoadState_LoadStateNotLoad   LoadState = 1
	LoadState_LoadStateLoading   LoadState = 2
	LoadState_LoadStateLoaded    LoadState = 3
	LoadState_LoadStateUnloading LoadState = 4
)

// Enum value maps for LoadState.
var (
	LoadState_name = map[int32]string{
		0: "LoadStateNotExist",
		1: "LoadStateNotLoad",
		2: "LoadStateLoading",
		3: "LoadStateLoaded",
		4: "LoadStateUnloading",
	}
	LoadState_value = map[string]int32{
		"LoadStateNotExist":  0,
		"LoadStateNotLoad":   1,
		"LoadStateLoading":   2,
		"LoadStateLoaded":    3,
		"LoadStateUnloading": 4,
	}
)

func (x LoadState) Enum() *LoadState {
	p := new(LoadState)
	*p = x
	return p
}

func (x LoadState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[8].Descriptor()
}

func (LoadState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[8]
}

func (x LoadState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadState.Descriptor instead.
func (LoadState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

// Status 状态信息
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.proto.ErrorCode" json:"error_code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_Success
}

func (x *Status) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// KeyValuePair 键值对
type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// KeyDataPair 键数据对
type KeyDataPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDataPair) Reset() {
	*x = KeyDataPair{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDataPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDataPair) ProtoMessage() {}

func (x *KeyDataPair) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDataPair.ProtoReflect.Descriptor instead.
func (*KeyDataPair) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *KeyDataPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyDataPair) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Blob 二进制数据
type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Blob) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PlaceholderValue 占位符值
type PlaceholderValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderValue) Reset() {
	*x = PlaceholderValue{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderValue) ProtoMessage() {}

func (x *PlaceholderValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderValue.ProtoReflect.Descriptor instead.
func (*PlaceholderValue) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceholderValue) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PlaceholderValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PlaceholderGroup 占位符组
type PlaceholderGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholders  []*PlaceholderValue    `protobuf:"bytes,1,rep,name=placeholders,proto3" json:"placeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderGroup) Reset() {
	*x = PlaceholderGroup{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderGroup) ProtoMessage() {}

func (x *PlaceholderGroup) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderGroup.ProtoReflect.Descriptor instead.
func (*PlaceholderGroup) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceholderGroup) GetPlaceholders() []*PlaceholderValue {
	if x != nil {
		return x.Placeholders
	}
	return nil
}

// Address 地址信息
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int64                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Address) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

// MsgBase 消息基础信息
type MsgBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       int64                  `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgID         int64                  `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceID      int64                  `protobuf:"varint,4,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBase) Reset() {
	*x = MsgBase{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBase) ProtoMessage() {}

func (x *MsgBase) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBase.ProtoReflect.Descriptor instead.
func (*MsgBase) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *MsgBase) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MsgBase) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *MsgBase) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MsgBase) GetSourceID() int64 {
	if x != nil {
		return x.SourceID
	}
	return 0
}

// MsgHeader 消息头
type MsgHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *MsgBase               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgHeader) Reset() {
	*x = MsgHeader{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHeader) ProtoMessage() {}

func (x *MsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHeader.ProtoReflect.Descriptor instead.
func (*MsgHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *MsgHeader) GetBase() *MsgBase {
	if x != nil {
		return x.Base
	}
	return nil
}

// DMLMsgHeader DML消息头
type DMLMsgHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *MsgBase               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ShardName     string                 `protobuf:"bytes,2,opt,name=shardName,proto3" json:"shardName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DMLMsgHeader) Reset() {
	*x = DMLMsgHeader{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMLMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMLMsgHeader) ProtoMessage() {}

func (x *DMLMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMLMsgHeader.ProtoReflect.Descriptor instead.
func (*DMLMsgHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *DMLMsgHeader) GetBase() *MsgBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DMLMsgHeader) GetShardName() string {
	if x != nil {
		return x.ShardName
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\fcommon.proto\"l\n" +
	"\x06Status\x126\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x17.common.proto.ErrorCodeR\terrorCode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\vKeyDataPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1c\n" +
	"\x04Blob\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\":\n" +
	"\x10PlaceholderValue\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"V\n" +
	"\x10PlaceholderGroup\x12B\n" +
	"\fplaceholders\x18\x01 \x03(\v2\x1e.common.proto.PlaceholderValueR\fplaceholders\"-\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\"t\n" +
	"\aMsgBase\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\x03R\amsgType\x12\x14\n" +
	"\x05msgID\x18\x02 \x01(\x03R\x05msgID\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bsourceID\x18\x04 \x01(\x03R\bsourceID\"6\n" +
	"\tMsgHeader\x12)\n" +
	"\x04base\x18\x01 \x01(\v2\x15.common.proto.MsgBaseR\x04base\"W\n" +
	"\fDMLMsgHeader\x12)\n" +
	"\x04base\x18\x01 \x01(\v2\x15.common.proto.MsgBaseR\x04base\x12\x1c\n" +
	"\tshardName\x18\x02 \x01(\tR\tshardName*\xea\n" +
	"\n" +
	"\tErrorCode\x12\v\n" +
	"\aSuccess\x10\x00\x12\x13\n" +
	"\x0fUnexpectedError\x10\x01\x12\x11\n" +
	"\rConnectFailed\x10\x02\x12\x14\n" +
	"\x10PermissionDenied\x10\x03\x12\x16\n" +
	"\x12CollectionNotFound\x10\x04\x12\x13\n" +
	"\x0fIllegalArgument\x10\x05\x12\x14\n" +
	"\x10IllegalDimension\x10\a\x12\x14\n" +
	"\x10IllegalIndexType\x10\b\x12\x19\n" +
	"\x15IllegalCollectionName\x10\t\x12\x0f\n" +
	"\vIllegalTOPK\x10\n" +
	"\x12\x14\n" +
	"\x10IllegalRowRecord\x10\v\x12\x13\n" +
	"\x0fIllegalVectorID\x10\f\x12\x17\n" +
	"\x13IllegalSearchResult\x10\r\x12\x10\n" +
	"\fFileNotFound\x10\x0e\x12\x0e\n" +
	"\n" +
	"MetaFailed\x10\x0f\x12\x0f\n" +
	"\vCacheFailed\x10\x10\x12\x16\n" +
	"\x12CannotCreateFolder\x10\x11\x12\x14\n" +
	"\x10CannotCreateFile\x10\x12\x12\x16\n" +
	"\x12CannotDeleteFolder\x10\x13\x12\x14\n" +
	"\x10CannotDeleteFile\x10\x14\x12\x13\n" +
	"\x0fBuildIndexError\x10\x15\x12\x10\n" +
	"\fIllegalNLIST\x10\x16\x12\x15\n" +
	"\x11IllegalMetricType\x10\x17\x12\x0f\n" +
	"\vOutOfMemory\x10\x18\x12\x11\n" +
	"\rIndexNotExist\x10\x19\x12\x13\n" +
	"\x0fEmptyCollection\x10\x1a\x12\x1b\n" +
	"\x17UpdateImportTaskFailure\x10\x1b\x12\x1a\n" +
	"\x16CollectionNameNotFound\x10\x1c\x12\x1b\n" +
	"\x17CreateCredentialFailure\x10\x1d\x12\x1b\n" +
	"\x17UpdateCredentialFailure\x10\x1e\x12\x1b\n" +
	"\x17DeleteCredentialFailure\x10\x1f\x12\x18\n" +
	"\x14GetCredentialFailure\x10 \x12\x18\n" +
	"\x14ListCredUsersFailure\x10!\x12\x12\n" +
	"\x0eGetUserFailure\x10\"\x12\x15\n" +
	"\x11CreateRoleFailure\x10#\x12\x13\n" +
	"\x0fDropRoleFailure\x10$\x12\x1a\n" +
	"\x16OperateUserRoleFailure\x10%\x12\x15\n" +
	"\x11SelectRoleFailure\x10&\x12\x15\n" +
	"\x11SelectUserFailure\x10'\x12\x19\n" +
	"\x15SelectResourceFailure\x10(\x12\x1b\n" +
	"\x17OperatePrivilegeFailure\x10)\x12\x16\n" +
	"\x12SelectGrantFailure\x10*\x12!\n" +
	"\x1dRefreshPolicyInfoCacheFailure\x10+\x12\x15\n" +
	"\x11ListPolicyFailure\x10,\x12\x12\n" +
	"\x0eNotShardLeader\x10-\x12\x16\n" +
	"\x12NoReplicaAvailable\x10.\x12\x13\n" +
	"\x0fSegmentNotFound\x10/\x12\r\n" +
	"\tForceDeny\x100\x12\r\n" +
	"\tRateLimit\x101\x12\x12\n" +
	"\x0eNodeIDNotMatch\x102\x12\x14\n" +
	"\x10UpsertAutoIDTrue\x103\x12\x1c\n" +
	"\x18InsufficientMemoryToLoad\x104\x12\x18\n" +
	"\x14MemoryQuotaExhausted\x105\x12\x16\n" +
	"\x12DiskQuotaExhausted\x106\x12\x15\n" +
	"\x11TimeTickLongDelay\x107\x12\x12\n" +
	"\x0eNotFoundTSafer\x108\x12\x11\n" +
	"\rDenyToRewrite\x109\x12\x13\n" +
	"\x0fInvalidPassword\x10:\x12\x11\n" +
	"\rDDRequestRace\x10;\x12\x0e\n" +
	"\n" +
	"DCNotReady\x10d\x12\x0e\n" +
	"\n" +
	"DNNotReady\x10e\x12\f\n" +
	"\bCGOError\x10f*X\n" +
	"\x10ConsistencyLevel\x12\n" +
	"\n" +
	"\x06Strong\x10\x00\x12\v\n" +
	"\aSession\x10\x01\x12\v\n" +
	"\aBounded\x10\x02\x12\x0e\n" +
	"\n" +
	"Eventually\x10\x03\x12\x0e\n" +
	"\n" +
	"Customized\x10\x04*B\n" +
	"\x0fCompactionState\x12\x11\n" +
	"\rUndefiedState\x10\x00\x12\r\n" +
	"\tExecuting\x10\x01\x12\r\n" +
	"\tCompleted\x10\x02*\x82\x01\n" +
	"\fSegmentState\x12\x14\n" +
	"\x10SegmentStateNone\x10\x00\x12\f\n" +
	"\bNotExist\x10\x01\x12\v\n" +
	"\aGrowing\x10\x02\x12\n" +
	"\n" +
	"\x06Sealed\x10\x03\x12\v\n" +
	"\aFlushed\x10\x04\x12\f\n" +
	"\bFlushing\x10\x05\x12\v\n" +
	"\aDropped\x10\x06\x12\r\n" +
	"\tImporting\x10\a*\x8b\x01\n" +
	"\vImportState\x12\x11\n" +
	"\rImportPending\x10\x00\x12\x10\n" +
	"\fImportFailed\x10\x01\x12\x11\n" +
	"\rImportStarted\x10\x02\x12\x13\n" +
	"\x0fImportPersisted\x10\x05\x12\x13\n" +
	"\x0fImportCompleted\x10\x06\x12\x1a\n" +
	"\x16ImportFailedAndCleaned\x10\a*G\n" +
	"\n" +
	"ObjectType\x12\x0e\n" +
	"\n" +
	"Collection\x10\x00\x12\n" +
	"\n" +
	"\x06Global\x10\x01\x12\b\n" +
	"\x04User\x10\x02\x12\x13\n" +
	"\x0fObjectTypeCount\x10\x03*\xb8\x05\n" +
	"\x0fObjectPrivilege\x12\x10\n" +
	"\fPrivilegeAll\x10\x00\x12\x13\n" +
	"\x0fPrivilegeCreate\x10\x01\x12\x11\n" +
	"\rPrivilegeDrop\x10\x02\x12\x12\n" +
	"\x0ePrivilegeAlter\x10\x03\x12\x11\n" +
	"\rPrivilegeRead\x10\x04\x12\x11\n" +
	"\rPrivilegeLoad\x10\x05\x12\x14\n" +
	"\x10PrivilegeRelease\x10\x06\x12\x14\n" +
	"\x10PrivilegeCompact\x10\a\x12\x13\n" +
	"\x0fPrivilegeInsert\x10\b\x12\x13\n" +
	"\x0fPrivilegeDelete\x10\t\x12\x1a\n" +
	"\x16PrivilegeGetStatistics\x10\n" +
	"\x12\x18\n" +
	"\x14PrivilegeCreateIndex\x10\v\x12\x18\n" +
	"\x14PrivilegeIndexDetail\x10\f\x12\x16\n" +
	"\x12PrivilegeDropIndex\x10\r\x12\x13\n" +
	"\x0fPrivilegeSearch\x10\x0e\x12\x12\n" +
	"\x0ePrivilegeFlush\x10\x0f\x12\x12\n" +
	"\x0ePrivilegeQuery\x10\x10\x12\x18\n" +
	"\x14PrivilegeLoadBalance\x10\x11\x12\x13\n" +
	"\x0fPrivilegeImport\x10\x12\x12\x13\n" +
	"\x0fPrivilegeBackup\x10\x13\x12\x14\n" +
	"\x10PrivilegeRestore\x10\x14\x12\x18\n" +
	"\x14PrivilegeListIndexes\x10\x15\x12\x1b\n" +
	"\x17PrivilegeCreateDatabase\x10\x16\x12\x19\n" +
	"\x15PrivilegeDropDatabase\x10\x17\x12\x1a\n" +
	"\x16PrivilegeListDatabases\x10\x18\x12\x1d\n" +
	"\x19PrivilegeDescribeDatabase\x10\x19\x12\x1a\n" +
	"\x16PrivilegeAlterDatabase\x10\x1a\x12\x1f\n" +
	"\x1bPrivilegeDescribeCollection\x10\x1b\x12\x12\n" +
	"\x0ePrivilegeCount\x10\x1c*S\n" +
	"\tStateCode\x12\x10\n" +
	"\fInitializing\x10\x00\x12\v\n" +
	"\aHealthy\x10\x01\x12\f\n" +
	"\bAbnormal\x10\x02\x12\v\n" +
	"\aStandBy\x10\x03\x12\f\n" +
	"\bStopping\x10\x04*{\n" +
	"\tLoadState\x12\x15\n" +
	"\x11LoadStateNotExist\x10\x00\x12\x14\n" +
	"\x10LoadStateNotLoad\x10\x01\x12\x14\n" +
	"\x10LoadStateLoading\x10\x02\x12\x13\n" +
	"\x0fLoadStateLoaded\x10\x03\x12\x16\n" +
	"\x12LoadStateUnloading\x10\x04B3Z1github.com/milvus-io/milvus/pkg/v2/proto/commonpbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_proto_goTypes = []any{
	(ErrorCode)(0),           // 0: common.proto.ErrorCode
	(ConsistencyLevel)(0),    // 1: common.proto.ConsistencyLevel
	(CompactionState)(0),     // 2: common.proto.CompactionState
	(SegmentState)(0),        // 3: common.proto.SegmentState
	(ImportState)(0),         // 4: common.proto.ImportState
	(ObjectType)(0),          // 5: common.proto.ObjectType
	(ObjectPrivilege)(0),     // 6: common.proto.ObjectPrivilege
	(StateCode)(0),           // 7: common.proto.StateCode
	(LoadState)(0),           // 8: common.proto.LoadState
	(*Status)(nil),           // 9: common.proto.Status
	(*KeyValuePair)(nil),     // 10: common.proto.KeyValuePair
	(*KeyDataPair)(nil),      // 11: common.proto.KeyDataPair
	(*Blob)(nil),             // 12: common.proto.Blob
	(*PlaceholderValue)(nil), // 13: common.proto.PlaceholderValue
	(*PlaceholderGroup)(nil), // 14: common.proto.PlaceholderGroup
	(*Address)(nil),          // 15: common.proto.Address
	(*MsgBase)(nil),          // 16: common.proto.MsgBase
	(*MsgHeader)(nil),        // 17: common.proto.MsgHeader
	(*DMLMsgHeader)(nil),     // 18: common.proto.DMLMsgHeader
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: common.proto.Status.error_code:type_name -> common.proto.ErrorCode
	13, // 1: common.proto.PlaceholderGroup.placeholders:type_name -> common.proto.PlaceholderValue
	16, // 2: common.proto.MsgHeader.base:type_name -> common.proto.MsgBase
	16, // 3: common.proto.DMLMsgHeader.base:type_name -> common.proto.MsgBase
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
