// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: memory.proto

package memorypb

import (
	commonpb "github.com/milvus-io/milvus/pkg/v2/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemoryType 记忆类型
type MemoryType int32

const (
	MemoryType_MEMORY_UNKNOWN MemoryType = 0
	MemoryType_EPISODIC       MemoryType = 1 // 情景记忆：发生过什么
	MemoryType_SEMANTIC       MemoryType = 2 // 语义记忆：抽象事实与知识
	MemoryType_PROCEDURAL     MemoryType = 3 // 程序记忆：规则、流程、策略
	MemoryType_SOCIAL         MemoryType = 4 // 社交/共享记忆：共享约定、团队状态
	MemoryType_REFLECTIVE     MemoryType = 5 // 反思记忆：反思、修正、经验结论
)

// Enum value maps for MemoryType.
var (
	MemoryType_name = map[int32]string{
		0: "MEMORY_UNKNOWN",
		1: "EPISODIC",
		2: "SEMANTIC",
		3: "PROCEDURAL",
		4: "SOCIAL",
		5: "REFLECTIVE",
	}
	MemoryType_value = map[string]int32{
		"MEMORY_UNKNOWN": 0,
		"EPISODIC":       1,
		"SEMANTIC":       2,
		"PROCEDURAL":     3,
		"SOCIAL":         4,
		"REFLECTIVE":     5,
	}
)

func (x MemoryType) Enum() *MemoryType {
	p := new(MemoryType)
	*p = x
	return p
}

func (x MemoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_memory_proto_enumTypes[0].Descriptor()
}

func (MemoryType) Type() protoreflect.EnumType {
	return &file_memory_proto_enumTypes[0]
}

func (x MemoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryType.Descriptor instead.
func (MemoryType) EnumDescriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

// MemoryLevel 记忆蒸馏层级
type MemoryLevel int32

const (
	MemoryLevel_LEVEL_UNKNOWN MemoryLevel = 0
	MemoryLevel_LEVEL_RAW     MemoryLevel = 1 // 原始记录
	MemoryLevel_LEVEL_SUMMARY MemoryLevel = 2 // 摘要
	MemoryLevel_LEVEL_PATTERN MemoryLevel = 3 // 归纳规律
)

// Enum value maps for MemoryLevel.
var (
	MemoryLevel_name = map[int32]string{
		0: "LEVEL_UNKNOWN",
		1: "LEVEL_RAW",
		2: "LEVEL_SUMMARY",
		3: "LEVEL_PATTERN",
	}
	MemoryLevel_value = map[string]int32{
		"LEVEL_UNKNOWN": 0,
		"LEVEL_RAW":     1,
		"LEVEL_SUMMARY": 2,
		"LEVEL_PATTERN": 3,
	}
)

func (x MemoryLevel) Enum() *MemoryLevel {
	p := new(MemoryLevel)
	*p = x
	return p
}

func (x MemoryLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_memory_proto_enumTypes[1].Descriptor()
}

func (MemoryLevel) Type() protoreflect.EnumType {
	return &file_memory_proto_enumTypes[1]
}

func (x MemoryLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryLevel.Descriptor instead.
func (MemoryLevel) EnumDescriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

// MemoryState 记忆状态
type MemoryState int32

const (
	MemoryState_MEMORY_STATE_UNKNOWN MemoryState = 0
	MemoryState_MEMORY_ACTIVE        MemoryState = 1
	MemoryState_MEMORY_FADING        MemoryState = 2
	MemoryState_MEMORY_ARCHIVED      MemoryState = 3
	MemoryState_MEMORY_QUARANTINED   MemoryState = 4
	MemoryState_MEMORY_DELETED       MemoryState = 5
)

// Enum value maps for MemoryState.
var (
	MemoryState_name = map[int32]string{
		0: "MEMORY_STATE_UNKNOWN",
		1: "MEMORY_ACTIVE",
		2: "MEMORY_FADING",
		3: "MEMORY_ARCHIVED",
		4: "MEMORY_QUARANTINED",
		5: "MEMORY_DELETED",
	}
	MemoryState_value = map[string]int32{
		"MEMORY_STATE_UNKNOWN": 0,
		"MEMORY_ACTIVE":        1,
		"MEMORY_FADING":        2,
		"MEMORY_ARCHIVED":      3,
		"MEMORY_QUARANTINED":   4,
		"MEMORY_DELETED":       5,
	}
)

func (x MemoryState) Enum() *MemoryState {
	p := new(MemoryState)
	*p = x
	return p
}

func (x MemoryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryState) Descriptor() protoreflect.EnumDescriptor {
	return file_memory_proto_enumTypes[2].Descriptor()
}

func (MemoryState) Type() protoreflect.EnumType {
	return &file_memory_proto_enumTypes[2]
}

func (x MemoryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryState.Descriptor instead.
func (MemoryState) EnumDescriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

// Memory 记忆对象
type Memory struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MemoryId   string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	MemoryType MemoryType             `protobuf:"varint,2,opt,name=memory_type,json=memoryType,proto3,enum=memory.proto.MemoryType" json:"memory_type,omitempty"`
	AgentId    string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId  string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope      string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Level      MemoryLevel            `protobuf:"varint,6,opt,name=level,proto3,enum=memory.proto.MemoryLevel" json:"level,omitempty"`
	// 内容
	Content        string   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Summary        string   `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	SourceEventIds []string `protobuf:"bytes,9,rep,name=source_event_ids,json=sourceEventIds,proto3" json:"source_event_ids,omitempty"`
	// 质量指标
	Confidence     float32 `protobuf:"fixed32,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Importance     float32 `protobuf:"fixed32,11,opt,name=importance,proto3" json:"importance,omitempty"`
	FreshnessScore float32 `protobuf:"fixed32,12,opt,name=freshness_score,json=freshnessScore,proto3" json:"freshness_score,omitempty"`
	// 生命周期
	Ttl       int64  `protobuf:"varint,13,opt,name=ttl,proto3" json:"ttl,omitempty"` // 存活时间（秒）
	ValidFrom uint64 `protobuf:"varint,14,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo   uint64 `protobuf:"varint,15,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	// 溯源
	ProvenanceRef string `protobuf:"bytes,16,opt,name=provenance_ref,json=provenanceRef,proto3" json:"provenance_ref,omitempty"`
	// 版本
	Version  int64       `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	IsActive bool        `protobuf:"varint,18,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	State    MemoryState `protobuf:"varint,19,opt,name=state,proto3,enum=memory.proto.MemoryState" json:"state,omitempty"`
	// 时间戳
	CreatedTs uint64 `protobuf:"varint,20,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs uint64 `protobuf:"varint,21,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	// 元数据
	Metadata map[string]string `protobuf:"bytes,22,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 向量引用（实际向量存储在Milvus中）
	EmbeddingRef    string    `protobuf:"bytes,23,opt,name=embedding_ref,json=embeddingRef,proto3" json:"embedding_ref,omitempty"`
	EmbeddingVector []float32 `protobuf:"fixed32,24,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *Memory) GetMemoryType() MemoryType {
	if x != nil {
		return x.MemoryType
	}
	return MemoryType_MEMORY_UNKNOWN
}

func (x *Memory) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Memory) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Memory) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Memory) GetLevel() MemoryLevel {
	if x != nil {
		return x.Level
	}
	return MemoryLevel_LEVEL_UNKNOWN
}

func (x *Memory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memory) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Memory) GetSourceEventIds() []string {
	if x != nil {
		return x.SourceEventIds
	}
	return nil
}

func (x *Memory) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Memory) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Memory) GetFreshnessScore() float32 {
	if x != nil {
		return x.FreshnessScore
	}
	return 0
}

func (x *Memory) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Memory) GetValidFrom() uint64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *Memory) GetValidTo() uint64 {
	if x != nil {
		return x.ValidTo
	}
	return 0
}

func (x *Memory) GetProvenanceRef() string {
	if x != nil {
		return x.ProvenanceRef
	}
	return ""
}

func (x *Memory) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Memory) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Memory) GetState() MemoryState {
	if x != nil {
		return x.State
	}
	return MemoryState_MEMORY_STATE_UNKNOWN
}

func (x *Memory) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *Memory) GetUpdatedTs() uint64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

func (x *Memory) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Memory) GetEmbeddingRef() string {
	if x != nil {
		return x.EmbeddingRef
	}
	return ""
}

func (x *Memory) GetEmbeddingVector() []float32 {
	if x != nil {
		return x.EmbeddingVector
	}
	return nil
}

// MemoryPolicy 记忆策略（Policy Layer）
type MemoryPolicy struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MemoryId string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	// 显著性权重
	SalienceWeight float32 `protobuf:"fixed32,2,opt,name=salience_weight,json=salienceWeight,proto3" json:"salience_weight,omitempty"`
	// TTL策略
	Ttl     int64  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DecayFn string `protobuf:"bytes,4,opt,name=decay_fn,json=decayFn,proto3" json:"decay_fn,omitempty"` // "linear", "exponential", "step"
	// 置信度
	Confidence float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// 验证状态
	Verified   bool   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	VerifiedBy string `protobuf:"bytes,7,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	VerifiedAt uint64 `protobuf:"varint,8,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	// 隔离状态
	Quarantined      bool   `protobuf:"varint,9,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	QuarantineReason string `protobuf:"bytes,10,opt,name=quarantine_reason,json=quarantineReason,proto3" json:"quarantine_reason,omitempty"`
	// 可见性策略
	VisibilityPolicy string `protobuf:"bytes,11,opt,name=visibility_policy,json=visibilityPolicy,proto3" json:"visibility_policy,omitempty"`
	// ACL
	ReadAcl   []string `protobuf:"bytes,12,rep,name=read_acl,json=readAcl,proto3" json:"read_acl,omitempty"`
	WriteAcl  []string `protobuf:"bytes,13,rep,name=write_acl,json=writeAcl,proto3" json:"write_acl,omitempty"`
	DeriveAcl []string `protobuf:"bytes,14,rep,name=derive_acl,json=deriveAcl,proto3" json:"derive_acl,omitempty"`
	// 策略来源
	PolicyReason  string `protobuf:"bytes,15,opt,name=policy_reason,json=policyReason,proto3" json:"policy_reason,omitempty"`
	PolicySource  string `protobuf:"bytes,16,opt,name=policy_source,json=policySource,proto3" json:"policy_source,omitempty"`
	PolicyEventId string `protobuf:"bytes,17,opt,name=policy_event_id,json=policyEventId,proto3" json:"policy_event_id,omitempty"`
	// 时间戳
	CreatedTs     uint64 `protobuf:"varint,18,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs     uint64 `protobuf:"varint,19,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryPolicy) Reset() {
	*x = MemoryPolicy{}
	mi := &file_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryPolicy) ProtoMessage() {}

func (x *MemoryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryPolicy.ProtoReflect.Descriptor instead.
func (*MemoryPolicy) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryPolicy) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *MemoryPolicy) GetSalienceWeight() float32 {
	if x != nil {
		return x.SalienceWeight
	}
	return 0
}

func (x *MemoryPolicy) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MemoryPolicy) GetDecayFn() string {
	if x != nil {
		return x.DecayFn
	}
	return ""
}

func (x *MemoryPolicy) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MemoryPolicy) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *MemoryPolicy) GetVerifiedBy() string {
	if x != nil {
		return x.VerifiedBy
	}
	return ""
}

func (x *MemoryPolicy) GetVerifiedAt() uint64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

func (x *MemoryPolicy) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

func (x *MemoryPolicy) GetQuarantineReason() string {
	if x != nil {
		return x.QuarantineReason
	}
	return ""
}

func (x *MemoryPolicy) GetVisibilityPolicy() string {
	if x != nil {
		return x.VisibilityPolicy
	}
	return ""
}

func (x *MemoryPolicy) GetReadAcl() []string {
	if x != nil {
		return x.ReadAcl
	}
	return nil
}

func (x *MemoryPolicy) GetWriteAcl() []string {
	if x != nil {
		return x.WriteAcl
	}
	return nil
}

func (x *MemoryPolicy) GetDeriveAcl() []string {
	if x != nil {
		return x.DeriveAcl
	}
	return nil
}

func (x *MemoryPolicy) GetPolicyReason() string {
	if x != nil {
		return x.PolicyReason
	}
	return ""
}

func (x *MemoryPolicy) GetPolicySource() string {
	if x != nil {
		return x.PolicySource
	}
	return ""
}

func (x *MemoryPolicy) GetPolicyEventId() string {
	if x != nil {
		return x.PolicyEventId
	}
	return ""
}

func (x *MemoryPolicy) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *MemoryPolicy) GetUpdatedTs() uint64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

// MemoryAdaptation 记忆适配（Adaptation Layer）
type MemoryAdaptation struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MemoryId string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	// 检索配置
	RetrievalProfile map[string]float32 `protobuf:"bytes,2,rep,name=retrieval_profile,json=retrievalProfile,proto3" json:"retrieval_profile,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// 排序参数
	RankingParams map[string]float32 `protobuf:"bytes,3,rep,name=ranking_params,json=rankingParams,proto3" json:"ranking_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// 过滤阈值
	FilteringThresholds map[string]float32 `protobuf:"bytes,4,rep,name=filtering_thresholds,json=filteringThresholds,proto3" json:"filtering_thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// 投影权重
	ProjectionWeights map[string]float32 `protobuf:"bytes,5,rep,name=projection_weights,json=projectionWeights,proto3" json:"projection_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// 嵌入模型选择
	EmbeddingFamily string `protobuf:"bytes,6,opt,name=embedding_family,json=embeddingFamily,proto3" json:"embedding_family,omitempty"`
	ModelId         string `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// 适配来源
	AdaptationReason string `protobuf:"bytes,8,opt,name=adaptation_reason,json=adaptationReason,proto3" json:"adaptation_reason,omitempty"`
	AdaptationSource string `protobuf:"bytes,9,opt,name=adaptation_source,json=adaptationSource,proto3" json:"adaptation_source,omitempty"`
	// 时间戳
	CreatedTs     uint64 `protobuf:"varint,10,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs     uint64 `protobuf:"varint,11,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryAdaptation) Reset() {
	*x = MemoryAdaptation{}
	mi := &file_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryAdaptation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryAdaptation) ProtoMessage() {}

func (x *MemoryAdaptation) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryAdaptation.ProtoReflect.Descriptor instead.
func (*MemoryAdaptation) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryAdaptation) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *MemoryAdaptation) GetRetrievalProfile() map[string]float32 {
	if x != nil {
		return x.RetrievalProfile
	}
	return nil
}

func (x *MemoryAdaptation) GetRankingParams() map[string]float32 {
	if x != nil {
		return x.RankingParams
	}
	return nil
}

func (x *MemoryAdaptation) GetFilteringThresholds() map[string]float32 {
	if x != nil {
		return x.FilteringThresholds
	}
	return nil
}

func (x *MemoryAdaptation) GetProjectionWeights() map[string]float32 {
	if x != nil {
		return x.ProjectionWeights
	}
	return nil
}

func (x *MemoryAdaptation) GetEmbeddingFamily() string {
	if x != nil {
		return x.EmbeddingFamily
	}
	return ""
}

func (x *MemoryAdaptation) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *MemoryAdaptation) GetAdaptationReason() string {
	if x != nil {
		return x.AdaptationReason
	}
	return ""
}

func (x *MemoryAdaptation) GetAdaptationSource() string {
	if x != nil {
		return x.AdaptationSource
	}
	return ""
}

func (x *MemoryAdaptation) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *MemoryAdaptation) GetUpdatedTs() uint64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

// State 状态对象
type State struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StateId            string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StateType          string                 `protobuf:"bytes,4,opt,name=state_type,json=stateType,proto3" json:"state_type,omitempty"`
	StateKey           string                 `protobuf:"bytes,5,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	StateValue         []byte                 `protobuf:"bytes,6,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	Version            int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	DerivedFromEventId string                 `protobuf:"bytes,8,opt,name=derived_from_event_id,json=derivedFromEventId,proto3" json:"derived_from_event_id,omitempty"`
	CheckpointTs       uint64                 `protobuf:"varint,9,opt,name=checkpoint_ts,json=checkpointTs,proto3" json:"checkpoint_ts,omitempty"`
	CreatedTs          uint64                 `protobuf:"varint,10,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs          uint64                 `protobuf:"varint,11,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{3}
}

func (x *State) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *State) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *State) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *State) GetStateType() string {
	if x != nil {
		return x.StateType
	}
	return ""
}

func (x *State) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

func (x *State) GetStateValue() []byte {
	if x != nil {
		return x.StateValue
	}
	return nil
}

func (x *State) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *State) GetDerivedFromEventId() string {
	if x != nil {
		return x.DerivedFromEventId
	}
	return ""
}

func (x *State) GetCheckpointTs() uint64 {
	if x != nil {
		return x.CheckpointTs
	}
	return 0
}

func (x *State) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *State) GetUpdatedTs() uint64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

func (x *State) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Artifact 外部工件
type Artifact struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId        string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OwnerAgentId      string                 `protobuf:"bytes,3,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	ArtifactType      string                 `protobuf:"bytes,4,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	Uri               string                 `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	ContentRef        string                 `protobuf:"bytes,6,opt,name=content_ref,json=contentRef,proto3" json:"content_ref,omitempty"`
	MimeType          string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Hash              string                 `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	ProducedByEventId string                 `protobuf:"bytes,10,opt,name=produced_by_event_id,json=producedByEventId,proto3" json:"produced_by_event_id,omitempty"`
	Version           int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedTs         uint64                 `protobuf:"varint,12,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{4}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Artifact) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *Artifact) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *Artifact) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Artifact) GetContentRef() string {
	if x != nil {
		return x.ContentRef
	}
	return ""
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Artifact) GetProducedByEventId() string {
	if x != nil {
		return x.ProducedByEventId
	}
	return ""
}

func (x *Artifact) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Artifact) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

// Relation 关系/边
type Relation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EdgeId           string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SrcObjectId      string                 `protobuf:"bytes,2,opt,name=src_object_id,json=srcObjectId,proto3" json:"src_object_id,omitempty"`
	SrcType          string                 `protobuf:"bytes,3,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"` // "memory", "event", "state", "artifact"
	DstObjectId      string                 `protobuf:"bytes,4,opt,name=dst_object_id,json=dstObjectId,proto3" json:"dst_object_id,omitempty"`
	DstType          string                 `protobuf:"bytes,5,opt,name=dst_type,json=dstType,proto3" json:"dst_type,omitempty"`
	RelationType     string                 `protobuf:"bytes,6,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"` // "caused_by", "derived_from", "supports", "contradicts", "summarizes", "updates", "uses_tool", "belongs_to_task", "shared_with"
	Weight           float32                `protobuf:"fixed32,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedTs        uint64                 `protobuf:"varint,9,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	CreatedByEventId string                 `protobuf:"bytes,10,opt,name=created_by_event_id,json=createdByEventId,proto3" json:"created_by_event_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{5}
}

func (x *Relation) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *Relation) GetSrcObjectId() string {
	if x != nil {
		return x.SrcObjectId
	}
	return ""
}

func (x *Relation) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *Relation) GetDstObjectId() string {
	if x != nil {
		return x.DstObjectId
	}
	return ""
}

func (x *Relation) GetDstType() string {
	if x != nil {
		return x.DstType
	}
	return ""
}

func (x *Relation) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *Relation) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Relation) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Relation) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *Relation) GetCreatedByEventId() string {
	if x != nil {
		return x.CreatedByEventId
	}
	return ""
}

// CreateMemoryRequest 创建记忆请求
type CreateMemoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId     string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentId         string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MemoryType      MemoryType             `protobuf:"varint,5,opt,name=memory_type,json=memoryType,proto3,enum=memory.proto.MemoryType" json:"memory_type,omitempty"`
	Scope           string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Content         string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Summary         string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	SourceEventIds  []string               `protobuf:"bytes,9,rep,name=source_event_ids,json=sourceEventIds,proto3" json:"source_event_ids,omitempty"`
	Confidence      float32                `protobuf:"fixed32,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Importance      float32                `protobuf:"fixed32,11,opt,name=importance,proto3" json:"importance,omitempty"`
	Ttl             int64                  `protobuf:"varint,12,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmbeddingVector []float32              `protobuf:"fixed32,14,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMemoryRequest) Reset() {
	*x = CreateMemoryRequest{}
	mi := &file_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryRequest) ProtoMessage() {}

func (x *CreateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateMemoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateMemoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateMemoryRequest) GetMemoryType() MemoryType {
	if x != nil {
		return x.MemoryType
	}
	return MemoryType_MEMORY_UNKNOWN
}

func (x *CreateMemoryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMemoryRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateMemoryRequest) GetSourceEventIds() []string {
	if x != nil {
		return x.SourceEventIds
	}
	return nil
}

func (x *CreateMemoryRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CreateMemoryRequest) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *CreateMemoryRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CreateMemoryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateMemoryRequest) GetEmbeddingVector() []float32 {
	if x != nil {
		return x.EmbeddingVector
	}
	return nil
}

// CreateMemoryResponse 创建记忆响应
type CreateMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MemoryId      string                 `protobuf:"bytes,2,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryResponse) Reset() {
	*x = CreateMemoryResponse{}
	mi := &file_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryResponse) ProtoMessage() {}

func (x *CreateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMemoryResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateMemoryResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *CreateMemoryResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetMemoryRequest 获取记忆请求
type GetMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`     // 0表示最新版本
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间旅行查询
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{8}
}

func (x *GetMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *GetMemoryRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetMemoryRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetMemoryResponse 获取记忆响应
type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Memory        *Memory                `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Policy        *MemoryPolicy          `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Adaptation    *MemoryAdaptation      `protobuf:"bytes,4,opt,name=adaptation,proto3" json:"adaptation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{9}
}

func (x *GetMemoryResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetMemoryResponse) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GetMemoryResponse) GetPolicy() *MemoryPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *GetMemoryResponse) GetAdaptation() *MemoryAdaptation {
	if x != nil {
		return x.Adaptation
	}
	return nil
}

// UpdateMemoryRequest 更新记忆请求
type UpdateMemoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MemoryId        string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Confidence      float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Importance      float32                `protobuf:"fixed32,5,opt,name=importance,proto3" json:"importance,omitempty"`
	Ttl             int64                  `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmbeddingVector []float32              `protobuf:"fixed32,8,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateMemoryRequest) Reset() {
	*x = UpdateMemoryRequest{}
	mi := &file_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryRequest) ProtoMessage() {}

func (x *UpdateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateMemoryRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateMemoryRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *UpdateMemoryRequest) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *UpdateMemoryRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *UpdateMemoryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateMemoryRequest) GetEmbeddingVector() []float32 {
	if x != nil {
		return x.EmbeddingVector
	}
	return nil
}

// UpdateMemoryResponse 更新记忆响应
type UpdateMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NewVersion    uint64                 `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoryResponse) Reset() {
	*x = UpdateMemoryResponse{}
	mi := &file_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryResponse) ProtoMessage() {}

func (x *UpdateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMemoryResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateMemoryResponse) GetNewVersion() uint64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

// DeleteMemoryRequest 删除记忆请求
type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"` // false表示软删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *DeleteMemoryRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

// DeleteMemoryResponse 删除记忆响应
type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMemoryResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// MemoryFilter 记忆过滤条件
type MemoryFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentIds       []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	SessionIds     []string               `protobuf:"bytes,2,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	MemoryTypes    []MemoryType           `protobuf:"varint,3,rep,packed,name=memory_types,json=memoryTypes,proto3,enum=memory.proto.MemoryType" json:"memory_types,omitempty"`
	Levels         []MemoryLevel          `protobuf:"varint,4,rep,packed,name=levels,proto3,enum=memory.proto.MemoryLevel" json:"levels,omitempty"`
	States         []MemoryState          `protobuf:"varint,5,rep,packed,name=states,proto3,enum=memory.proto.MemoryState" json:"states,omitempty"`
	Scope          string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	StartTime      uint64                 `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        uint64                 `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinConfidence  float32                `protobuf:"fixed32,9,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	MinImportance  float32                `protobuf:"fixed32,10,opt,name=min_importance,json=minImportance,proto3" json:"min_importance,omitempty"`
	MetadataFilter map[string]string      `protobuf:"bytes,11,rep,name=metadata_filter,json=metadataFilter,proto3" json:"metadata_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryFilter) Reset() {
	*x = MemoryFilter{}
	mi := &file_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryFilter) ProtoMessage() {}

func (x *MemoryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryFilter.ProtoReflect.Descriptor instead.
func (*MemoryFilter) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{14}
}

func (x *MemoryFilter) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *MemoryFilter) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *MemoryFilter) GetMemoryTypes() []MemoryType {
	if x != nil {
		return x.MemoryTypes
	}
	return nil
}

func (x *MemoryFilter) GetLevels() []MemoryLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *MemoryFilter) GetStates() []MemoryState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *MemoryFilter) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *MemoryFilter) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MemoryFilter) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MemoryFilter) GetMinConfidence() float32 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

func (x *MemoryFilter) GetMinImportance() float32 {
	if x != nil {
		return x.MinImportance
	}
	return 0
}

func (x *MemoryFilter) GetMetadataFilter() map[string]string {
	if x != nil {
		return x.MetadataFilter
	}
	return nil
}

// QueryMemoriesRequest 查询记忆请求
type QueryMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *MemoryFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Ascending     bool                   `protobuf:"varint,5,opt,name=ascending,proto3" json:"ascending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMemoriesRequest) Reset() {
	*x = QueryMemoriesRequest{}
	mi := &file_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMemoriesRequest) ProtoMessage() {}

func (x *QueryMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMemoriesRequest.ProtoReflect.Descriptor instead.
func (*QueryMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{15}
}

func (x *QueryMemoriesRequest) GetFilter() *MemoryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryMemoriesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryMemoriesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryMemoriesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *QueryMemoriesRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

// QueryMemoriesResponse 查询记忆响应
type QueryMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Memories      []*Memory              `protobuf:"bytes,2,rep,name=memories,proto3" json:"memories,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMemoriesResponse) Reset() {
	*x = QueryMemoriesResponse{}
	mi := &file_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMemoriesResponse) ProtoMessage() {}

func (x *QueryMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMemoriesResponse.ProtoReflect.Descriptor instead.
func (*QueryMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{16}
}

func (x *QueryMemoriesResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryMemoriesResponse) GetMemories() []*Memory {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *QueryMemoriesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// SearchMemoriesRequest 向量搜索记忆请求
type SearchMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	QueryVector   []float32              `protobuf:"fixed32,3,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK          int64                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter        *MemoryFilter          `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	MinScore      float32                `protobuf:"fixed32,6,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesRequest) Reset() {
	*x = SearchMemoriesRequest{}
	mi := &file_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesRequest) ProtoMessage() {}

func (x *SearchMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{17}
}

func (x *SearchMemoriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchMemoriesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SearchMemoriesRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchMemoriesRequest) GetTopK() int64 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchMemoriesRequest) GetFilter() *MemoryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchMemoriesRequest) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

// SearchResult 搜索结果
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *Memory                `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{18}
}

func (x *SearchResult) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// SearchMemoriesResponse 向量搜索记忆响应
type SearchMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesResponse) Reset() {
	*x = SearchMemoriesResponse{}
	mi := &file_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesResponse) ProtoMessage() {}

func (x *SearchMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{19}
}

func (x *SearchMemoriesResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SearchMemoriesResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// GetRelationsRequest 获取关系请求
type GetRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectType    string                 `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	RelationType  string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Hop           int64                  `protobuf:"varint,4,opt,name=hop,proto3" json:"hop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsRequest) Reset() {
	*x = GetRelationsRequest{}
	mi := &file_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsRequest) ProtoMessage() {}

func (x *GetRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetRelationsRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{20}
}

func (x *GetRelationsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetRelationsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetRelationsRequest) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *GetRelationsRequest) GetHop() int64 {
	if x != nil {
		return x.Hop
	}
	return 0
}

// GetRelationsResponse 获取关系响应
type GetRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Relations     []*Relation            `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsResponse) Reset() {
	*x = GetRelationsResponse{}
	mi := &file_memory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsResponse) ProtoMessage() {}

func (x *GetRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsResponse.ProtoReflect.Descriptor instead.
func (*GetRelationsResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{21}
}

func (x *GetRelationsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetRelationsResponse) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

// CreateRelationRequest 创建关系请求
type CreateRelationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SrcObjectId      string                 `protobuf:"bytes,1,opt,name=src_object_id,json=srcObjectId,proto3" json:"src_object_id,omitempty"`
	SrcType          string                 `protobuf:"bytes,2,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	DstObjectId      string                 `protobuf:"bytes,3,opt,name=dst_object_id,json=dstObjectId,proto3" json:"dst_object_id,omitempty"`
	DstType          string                 `protobuf:"bytes,4,opt,name=dst_type,json=dstType,proto3" json:"dst_type,omitempty"`
	RelationType     string                 `protobuf:"bytes,5,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Weight           float32                `protobuf:"fixed32,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedByEventId string                 `protobuf:"bytes,8,opt,name=created_by_event_id,json=createdByEventId,proto3" json:"created_by_event_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRelationRequest) Reset() {
	*x = CreateRelationRequest{}
	mi := &file_memory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationRequest) ProtoMessage() {}

func (x *CreateRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationRequest.ProtoReflect.Descriptor instead.
func (*CreateRelationRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRelationRequest) GetSrcObjectId() string {
	if x != nil {
		return x.SrcObjectId
	}
	return ""
}

func (x *CreateRelationRequest) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *CreateRelationRequest) GetDstObjectId() string {
	if x != nil {
		return x.DstObjectId
	}
	return ""
}

func (x *CreateRelationRequest) GetDstType() string {
	if x != nil {
		return x.DstType
	}
	return ""
}

func (x *CreateRelationRequest) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *CreateRelationRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateRelationRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *CreateRelationRequest) GetCreatedByEventId() string {
	if x != nil {
		return x.CreatedByEventId
	}
	return ""
}

// CreateRelationResponse 创建关系响应
type CreateRelationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRelationResponse) Reset() {
	*x = CreateRelationResponse{}
	mi := &file_memory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationResponse) ProtoMessage() {}

func (x *CreateRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationResponse.ProtoReflect.Descriptor instead.
func (*CreateRelationResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{23}
}

func (x *CreateRelationResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateRelationResponse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

var File_memory_proto protoreflect.FileDescriptor

const file_memory_proto_rawDesc = "" +
	"\n" +
	"\fmemory.proto\x12\fmemory.proto\x1a\fcommon.proto\"\x8e\a\n" +
	"\x06Memory\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x129\n" +
	"\vmemory_type\x18\x02 \x01(\x0e2\x18.memory.proto.MemoryTypeR\n" +
	"memoryType\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12/\n" +
	"\x05level\x18\x06 \x01(\x0e2\x19.memory.proto.MemoryLevelR\x05level\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12(\n" +
	"\x10source_event_ids\x18\t \x03(\tR\x0esourceEventIds\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"importance\x18\v \x01(\x02R\n" +
	"importance\x12'\n" +
	"\x0ffreshness_score\x18\f \x01(\x02R\x0efreshnessScore\x12\x10\n" +
	"\x03ttl\x18\r \x01(\x03R\x03ttl\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x0e \x01(\x04R\tvalidFrom\x12\x19\n" +
	"\bvalid_to\x18\x0f \x01(\x04R\avalidTo\x12%\n" +
	"\x0eprovenance_ref\x18\x10 \x01(\tR\rprovenanceRef\x12\x18\n" +
	"\aversion\x18\x11 \x01(\x03R\aversion\x12\x1b\n" +
	"\tis_active\x18\x12 \x01(\bR\bisActive\x12/\n" +
	"\x05state\x18\x13 \x01(\x0e2\x19.memory.proto.MemoryStateR\x05state\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x14 \x01(\x04R\tcreatedTs\x12\x1d\n" +
	"\n" +
	"updated_ts\x18\x15 \x01(\x04R\tupdatedTs\x12>\n" +
	"\bmetadata\x18\x16 \x03(\v2\".memory.proto.Memory.MetadataEntryR\bmetadata\x12#\n" +
	"\rembedding_ref\x18\x17 \x01(\tR\fembeddingRef\x12)\n" +
	"\x10embedding_vector\x18\x18 \x03(\x02R\x0fembeddingVector\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x05\n" +
	"\fMemoryPolicy\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12'\n" +
	"\x0fsalience_weight\x18\x02 \x01(\x02R\x0esalienceWeight\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x12\x19\n" +
	"\bdecay_fn\x18\x04 \x01(\tR\adecayFn\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12\x1f\n" +
	"\vverified_by\x18\a \x01(\tR\n" +
	"verifiedBy\x12\x1f\n" +
	"\vverified_at\x18\b \x01(\x04R\n" +
	"verifiedAt\x12 \n" +
	"\vquarantined\x18\t \x01(\bR\vquarantined\x12+\n" +
	"\x11quarantine_reason\x18\n" +
	" \x01(\tR\x10quarantineReason\x12+\n" +
	"\x11visibility_policy\x18\v \x01(\tR\x10visibilityPolicy\x12\x19\n" +
	"\bread_acl\x18\f \x03(\tR\areadAcl\x12\x1b\n" +
	"\twrite_acl\x18\r \x03(\tR\bwriteAcl\x12\x1d\n" +
	"\n" +
	"derive_acl\x18\x0e \x03(\tR\tderiveAcl\x12#\n" +
	"\rpolicy_reason\x18\x0f \x01(\tR\fpolicyReason\x12#\n" +
	"\rpolicy_source\x18\x10 \x01(\tR\fpolicySource\x12&\n" +
	"\x0fpolicy_event_id\x18\x11 \x01(\tR\rpolicyEventId\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x12 \x01(\x04R\tcreatedTs\x12\x1d\n" +
	"\n" +
	"updated_ts\x18\x13 \x01(\x04R\tupdatedTs\"\xb1\a\n" +
	"\x10MemoryAdaptation\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12a\n" +
	"\x11retrieval_profile\x18\x02 \x03(\v24.memory.proto.MemoryAdaptation.RetrievalProfileEntryR\x10retrievalProfile\x12X\n" +
	"\x0eranking_params\x18\x03 \x03(\v21.memory.proto.MemoryAdaptation.RankingParamsEntryR\rrankingParams\x12j\n" +
	"\x14filtering_thresholds\x18\x04 \x03(\v27.memory.proto.MemoryAdaptation.FilteringThresholdsEntryR\x13filteringThresholds\x12d\n" +
	"\x12projection_weights\x18\x05 \x03(\v25.memory.proto.MemoryAdaptation.ProjectionWeightsEntryR\x11projectionWeights\x12)\n" +
	"\x10embedding_family\x18\x06 \x01(\tR\x0fembeddingFamily\x12\x19\n" +
	"\bmodel_id\x18\a \x01(\tR\amodelId\x12+\n" +
	"\x11adaptation_reason\x18\b \x01(\tR\x10adaptationReason\x12+\n" +
	"\x11adaptation_source\x18\t \x01(\tR\x10adaptationSource\x12\x1d\n" +
	"\n" +
	"created_ts\x18\n" +
	" \x01(\x04R\tcreatedTs\x12\x1d\n" +
	"\n" +
	"updated_ts\x18\v \x01(\x04R\tupdatedTs\x1aC\n" +
	"\x15RetrievalProfileEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a@\n" +
	"\x12RankingParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aF\n" +
	"\x18FilteringThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aD\n" +
	"\x16ProjectionWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xe5\x03\n" +
	"\x05State\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"state_type\x18\x04 \x01(\tR\tstateType\x12\x1b\n" +
	"\tstate_key\x18\x05 \x01(\tR\bstateKey\x12\x1f\n" +
	"\vstate_value\x18\x06 \x01(\fR\n" +
	"stateValue\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x121\n" +
	"\x15derived_from_event_id\x18\b \x01(\tR\x12derivedFromEventId\x12#\n" +
	"\rcheckpoint_ts\x18\t \x01(\x04R\fcheckpointTs\x12\x1d\n" +
	"\n" +
	"created_ts\x18\n" +
	" \x01(\x04R\tcreatedTs\x12\x1d\n" +
	"\n" +
	"updated_ts\x18\v \x01(\x04R\tupdatedTs\x12=\n" +
	"\bmetadata\x18\f \x03(\v2!.memory.proto.State.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x03\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12$\n" +
	"\x0eowner_agent_id\x18\x03 \x01(\tR\fownerAgentId\x12#\n" +
	"\rartifact_type\x18\x04 \x01(\tR\fartifactType\x12\x10\n" +
	"\x03uri\x18\x05 \x01(\tR\x03uri\x12\x1f\n" +
	"\vcontent_ref\x18\x06 \x01(\tR\n" +
	"contentRef\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12@\n" +
	"\bmetadata\x18\b \x03(\v2$.memory.proto.Artifact.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04hash\x18\t \x01(\tR\x04hash\x12/\n" +
	"\x14produced_by_event_id\x18\n" +
	" \x01(\tR\x11producedByEventId\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_ts\x18\f \x01(\x04R\tcreatedTs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x03\n" +
	"\bRelation\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\"\n" +
	"\rsrc_object_id\x18\x02 \x01(\tR\vsrcObjectId\x12\x19\n" +
	"\bsrc_type\x18\x03 \x01(\tR\asrcType\x12\"\n" +
	"\rdst_object_id\x18\x04 \x01(\tR\vdstObjectId\x12\x19\n" +
	"\bdst_type\x18\x05 \x01(\tR\adstType\x12#\n" +
	"\rrelation_type\x18\x06 \x01(\tR\frelationType\x12\x16\n" +
	"\x06weight\x18\a \x01(\x02R\x06weight\x12F\n" +
	"\n" +
	"properties\x18\b \x03(\v2&.memory.proto.Relation.PropertiesEntryR\n" +
	"properties\x12\x1d\n" +
	"\n" +
	"created_ts\x18\t \x01(\x04R\tcreatedTs\x12-\n" +
	"\x13created_by_event_id\x18\n" +
	" \x01(\tR\x10createdByEventId\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x04\n" +
	"\x13CreateMemoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x129\n" +
	"\vmemory_type\x18\x05 \x01(\x0e2\x18.memory.proto.MemoryTypeR\n" +
	"memoryType\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12(\n" +
	"\x10source_event_ids\x18\t \x03(\tR\x0esourceEventIds\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"importance\x18\v \x01(\x02R\n" +
	"importance\x12\x10\n" +
	"\x03ttl\x18\f \x01(\x03R\x03ttl\x12K\n" +
	"\bmetadata\x18\r \x03(\v2/.memory.proto.CreateMemoryRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10embedding_vector\x18\x0e \x03(\x02R\x0fembeddingVector\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x14CreateMemoryResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12\x1b\n" +
	"\tmemory_id\x18\x02 \x01(\tR\bmemoryId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"g\n" +
	"\x10GetMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\xe3\x01\n" +
	"\x11GetMemoryResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12,\n" +
	"\x06memory\x18\x02 \x01(\v2\x14.memory.proto.MemoryR\x06memory\x122\n" +
	"\x06policy\x18\x03 \x01(\v2\x1a.memory.proto.MemoryPolicyR\x06policy\x12>\n" +
	"\n" +
	"adaptation\x18\x04 \x01(\v2\x1e.memory.proto.MemoryAdaptationR\n" +
	"adaptation\"\xed\x02\n" +
	"\x13UpdateMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x02R\n" +
	"importance\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttl\x12K\n" +
	"\bmetadata\x18\a \x03(\v2/.memory.proto.UpdateMemoryRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10embedding_vector\x18\b \x03(\x02R\x0fembeddingVector\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x14UpdateMemoryResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x04R\n" +
	"newVersion\"S\n" +
	"\x13DeleteMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\"D\n" +
	"\x14DeleteMemoryResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\"\xa9\x04\n" +
	"\fMemoryFilter\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\x12\x1f\n" +
	"\vsession_ids\x18\x02 \x03(\tR\n" +
	"sessionIds\x12;\n" +
	"\fmemory_types\x18\x03 \x03(\x0e2\x18.memory.proto.MemoryTypeR\vmemoryTypes\x121\n" +
	"\x06levels\x18\x04 \x03(\x0e2\x19.memory.proto.MemoryLevelR\x06levels\x121\n" +
	"\x06states\x18\x05 \x03(\x0e2\x19.memory.proto.MemoryStateR\x06states\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x04R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x04R\aendTime\x12%\n" +
	"\x0emin_confidence\x18\t \x01(\x02R\rminConfidence\x12%\n" +
	"\x0emin_importance\x18\n" +
	" \x01(\x02R\rminImportance\x12W\n" +
	"\x0fmetadata_filter\x18\v \x03(\v2..memory.proto.MemoryFilter.MetadataFilterEntryR\x0emetadataFilter\x1aA\n" +
	"\x13MetadataFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x14QueryMemoriesRequest\x122\n" +
	"\x06filter\x18\x01 \x01(\v2\x1a.memory.proto.MemoryFilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12\x1c\n" +
	"\tascending\x18\x05 \x01(\bR\tascending\"\x98\x01\n" +
	"\x15QueryMemoriesResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x120\n" +
	"\bmemories\x18\x02 \x03(\v2\x14.memory.proto.MemoryR\bmemories\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\"\xe0\x01\n" +
	"\x15SearchMemoriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12!\n" +
	"\fquery_vector\x18\x03 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x03R\x04topK\x122\n" +
	"\x06filter\x18\x05 \x01(\v2\x1a.memory.proto.MemoryFilterR\x06filter\x12\x1b\n" +
	"\tmin_score\x18\x06 \x01(\x02R\bminScore\"t\n" +
	"\fSearchResult\x12,\n" +
	"\x06memory\x18\x01 \x01(\v2\x14.memory.proto.MemoryR\x06memory\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\"|\n" +
	"\x16SearchMemoriesResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x124\n" +
	"\aresults\x18\x02 \x03(\v2\x1a.memory.proto.SearchResultR\aresults\"\x8a\x01\n" +
	"\x13GetRelationsRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\tR\n" +
	"objectType\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x12\x10\n" +
	"\x03hop\x18\x04 \x01(\x03R\x03hop\"z\n" +
	"\x14GetRelationsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x124\n" +
	"\trelations\x18\x02 \x03(\v2\x16.memory.proto.RelationR\trelations\"\x95\x03\n" +
	"\x15CreateRelationRequest\x12\"\n" +
	"\rsrc_object_id\x18\x01 \x01(\tR\vsrcObjectId\x12\x19\n" +
	"\bsrc_type\x18\x02 \x01(\tR\asrcType\x12\"\n" +
	"\rdst_object_id\x18\x03 \x01(\tR\vdstObjectId\x12\x19\n" +
	"\bdst_type\x18\x04 \x01(\tR\adstType\x12#\n" +
	"\rrelation_type\x18\x05 \x01(\tR\frelationType\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x02R\x06weight\x12S\n" +
	"\n" +
	"properties\x18\a \x03(\v23.memory.proto.CreateRelationRequest.PropertiesEntryR\n" +
	"properties\x12-\n" +
	"\x13created_by_event_id\x18\b \x01(\tR\x10createdByEventId\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x16CreateRelationResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId*h\n" +
	"\n" +
	"MemoryType\x12\x12\n" +
	"\x0eMEMORY_UNKNOWN\x10\x00\x12\f\n" +
	"\bEPISODIC\x10\x01\x12\f\n" +
	"\bSEMANTIC\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCEDURAL\x10\x03\x12\n" +
	"\n" +
	"\x06SOCIAL\x10\x04\x12\x0e\n" +
	"\n" +
	"REFLECTIVE\x10\x05*U\n" +
	"\vMemoryLevel\x12\x11\n" +
	"\rLEVEL_UNKNOWN\x10\x00\x12\r\n" +
	"\tLEVEL_RAW\x10\x01\x12\x11\n" +
	"\rLEVEL_SUMMARY\x10\x02\x12\x11\n" +
	"\rLEVEL_PATTERN\x10\x03*\x8e\x01\n" +
	"\vMemoryState\x12\x18\n" +
	"\x14MEMORY_STATE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rMEMORY_ACTIVE\x10\x01\x12\x11\n" +
	"\rMEMORY_FADING\x10\x02\x12\x13\n" +
	"\x0fMEMORY_ARCHIVED\x10\x03\x12\x16\n" +
	"\x12MEMORY_QUARANTINED\x10\x04\x12\x12\n" +
	"\x0eMEMORY_DELETED\x10\x052\xcd\x05\n" +
	"\rMemoryService\x12U\n" +
	"\fCreateMemory\x12!.memory.proto.CreateMemoryRequest\x1a\".memory.proto.CreateMemoryResponse\x12L\n" +
	"\tGetMemory\x12\x1e.memory.proto.GetMemoryRequest\x1a\x1f.memory.proto.GetMemoryResponse\x12U\n" +
	"\fUpdateMemory\x12!.memory.proto.UpdateMemoryRequest\x1a\".memory.proto.UpdateMemoryResponse\x12U\n" +
	"\fDeleteMemory\x12!.memory.proto.DeleteMemoryRequest\x1a\".memory.proto.DeleteMemoryResponse\x12X\n" +
	"\rQueryMemories\x12\".memory.proto.QueryMemoriesRequest\x1a#.memory.proto.QueryMemoriesResponse\x12[\n" +
	"\x0eSearchMemories\x12#.memory.proto.SearchMemoriesRequest\x1a$.memory.proto.SearchMemoriesResponse\x12U\n" +
	"\fGetRelations\x12!.memory.proto.GetRelationsRequest\x1a\".memory.proto.GetRelationsResponse\x12[\n" +
	"\x0eCreateRelation\x12#.memory.proto.CreateRelationRequest\x1a$.memory.proto.CreateRelationResponseB3Z1github.com/milvus-io/milvus/pkg/v2/proto/memorypbb\x06proto3"

var (
	file_memory_proto_rawDescOnce sync.Once
	file_memory_proto_rawDescData []byte
)

func file_memory_proto_rawDescGZIP() []byte {
	file_memory_proto_rawDescOnce.Do(func() {
		file_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)))
	})
	return file_memory_proto_rawDescData
}

var file_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_memory_proto_goTypes = []any{
	(MemoryType)(0),                // 0: memory.proto.MemoryType
	(MemoryLevel)(0),               // 1: memory.proto.MemoryLevel
	(MemoryState)(0),               // 2: memory.proto.MemoryState
	(*Memory)(nil),                 // 3: memory.proto.Memory
	(*MemoryPolicy)(nil),           // 4: memory.proto.MemoryPolicy
	(*MemoryAdaptation)(nil),       // 5: memory.proto.MemoryAdaptation
	(*State)(nil),                  // 6: memory.proto.State
	(*Artifact)(nil),               // 7: memory.proto.Artifact
	(*Relation)(nil),               // 8: memory.proto.Relation
	(*CreateMemoryRequest)(nil),    // 9: memory.proto.CreateMemoryRequest
	(*CreateMemoryResponse)(nil),   // 10: memory.proto.CreateMemoryResponse
	(*GetMemoryRequest)(nil),       // 11: memory.proto.GetMemoryRequest
	(*GetMemoryResponse)(nil),      // 12: memory.proto.GetMemoryResponse
	(*UpdateMemoryRequest)(nil),    // 13: memory.proto.UpdateMemoryRequest
	(*UpdateMemoryResponse)(nil),   // 14: memory.proto.UpdateMemoryResponse
	(*DeleteMemoryRequest)(nil),    // 15: memory.proto.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil),   // 16: memory.proto.DeleteMemoryResponse
	(*MemoryFilter)(nil),           // 17: memory.proto.MemoryFilter
	(*QueryMemoriesRequest)(nil),   // 18: memory.proto.QueryMemoriesRequest
	(*QueryMemoriesResponse)(nil),  // 19: memory.proto.QueryMemoriesResponse
	(*SearchMemoriesRequest)(nil),  // 20: memory.proto.SearchMemoriesRequest
	(*SearchResult)(nil),           // 21: memory.proto.SearchResult
	(*SearchMemoriesResponse)(nil), // 22: memory.proto.SearchMemoriesResponse
	(*GetRelationsRequest)(nil),    // 23: memory.proto.GetRelationsRequest
	(*GetRelationsResponse)(nil),   // 24: memory.proto.GetRelationsResponse
	(*CreateRelationRequest)(nil),  // 25: memory.proto.CreateRelationRequest
	(*CreateRelationResponse)(nil), // 26: memory.proto.CreateRelationResponse
	nil,                            // 27: memory.proto.Memory.MetadataEntry
	nil,                            // 28: memory.proto.MemoryAdaptation.RetrievalProfileEntry
	nil,                            // 29: memory.proto.MemoryAdaptation.RankingParamsEntry
	nil,                            // 30: memory.proto.MemoryAdaptation.FilteringThresholdsEntry
	nil,                            // 31: memory.proto.MemoryAdaptation.ProjectionWeightsEntry
	nil,                            // 32: memory.proto.State.MetadataEntry
	nil,                            // 33: memory.proto.Artifact.MetadataEntry
	nil,                            // 34: memory.proto.Relation.PropertiesEntry
	nil,                            // 35: memory.proto.CreateMemoryRequest.MetadataEntry
	nil,                            // 36: memory.proto.UpdateMemoryRequest.MetadataEntry
	nil,                            // 37: memory.proto.MemoryFilter.MetadataFilterEntry
	nil,                            // 38: memory.proto.CreateRelationRequest.PropertiesEntry
	(*commonpb.Status)(nil),        // 39: common.proto.Status
}
var file_memory_proto_depIdxs = []int32{
	0,  // 0: memory.proto.Memory.memory_type:type_name -> memory.proto.MemoryType
	1,  // 1: memory.proto.Memory.level:type_name -> memory.proto.MemoryLevel
	2,  // 2: memory.proto.Memory.state:type_name -> memory.proto.MemoryState
	27, // 3: memory.proto.Memory.metadata:type_name -> memory.proto.Memory.MetadataEntry
	28, // 4: memory.proto.MemoryAdaptation.retrieval_profile:type_name -> memory.proto.MemoryAdaptation.RetrievalProfileEntry
	29, // 5: memory.proto.MemoryAdaptation.ranking_params:type_name -> memory.proto.MemoryAdaptation.RankingParamsEntry
	30, // 6: memory.proto.MemoryAdaptation.filtering_thresholds:type_name -> memory.proto.MemoryAdaptation.FilteringThresholdsEntry
	31, // 7: memory.proto.MemoryAdaptation.projection_weights:type_name -> memory.proto.MemoryAdaptation.ProjectionWeightsEntry
	32, // 8: memory.proto.State.metadata:type_name -> memory.proto.State.MetadataEntry
	33, // 9: memory.proto.Artifact.metadata:type_name -> memory.proto.Artifact.MetadataEntry
	34, // 10: memory.proto.Relation.properties:type_name -> memory.proto.Relation.PropertiesEntry
	0,  // 11: memory.proto.CreateMemoryRequest.memory_type:type_name -> memory.proto.MemoryType
	35, // 12: memory.proto.CreateMemoryRequest.metadata:type_name -> memory.proto.CreateMemoryRequest.MetadataEntry
	39, // 13: memory.proto.CreateMemoryResponse.status:type_name -> common.proto.Status
	39, // 14: memory.proto.GetMemoryResponse.status:type_name -> common.proto.Status
	3,  // 15: memory.proto.GetMemoryResponse.memory:type_name -> memory.proto.Memory
	4,  // 16: memory.proto.GetMemoryResponse.policy:type_name -> memory.proto.MemoryPolicy
	5,  // 17: memory.proto.GetMemoryResponse.adaptation:type_name -> memory.proto.MemoryAdaptation
	36, // 18: memory.proto.UpdateMemoryRequest.metadata:type_name -> memory.proto.UpdateMemoryRequest.MetadataEntry
	39, // 19: memory.proto.UpdateMemoryResponse.status:type_name -> common.proto.Status
	39, // 20: memory.proto.DeleteMemoryResponse.status:type_name -> common.proto.Status
	0,  // 21: memory.proto.MemoryFilter.memory_types:type_name -> memory.proto.MemoryType
	1,  // 22: memory.proto.MemoryFilter.levels:type_name -> memory.proto.MemoryLevel
	2,  // 23: memory.proto.MemoryFilter.states:type_name -> memory.proto.MemoryState
	37, // 24: memory.proto.MemoryFilter.metadata_filter:type_name -> memory.proto.MemoryFilter.MetadataFilterEntry
	17, // 25: memory.proto.QueryMemoriesRequest.filter:type_name -> memory.proto.MemoryFilter
	39, // 26: memory.proto.QueryMemoriesResponse.status:type_name -> common.proto.Status
	3,  // 27: memory.proto.QueryMemoriesResponse.memories:type_name -> memory.proto.Memory
	17, // 28: memory.proto.SearchMemoriesRequest.filter:type_name -> memory.proto.MemoryFilter
	3,  // 29: memory.proto.SearchResult.memory:type_name -> memory.proto.Memory
	39, // 30: memory.proto.SearchMemoriesResponse.status:type_name -> common.proto.Status
	21, // 31: memory.proto.SearchMemoriesResponse.results:type_name -> memory.proto.SearchResult
	39, // 32: memory.proto.GetRelationsResponse.status:type_name -> common.proto.Status
	8,  // 33: memory.proto.GetRelationsResponse.relations:type_name -> memory.proto.Relation
	38, // 34: memory.proto.CreateRelationRequest.properties:type_name -> memory.proto.CreateRelationRequest.PropertiesEntry
	39, // 35: memory.proto.CreateRelationResponse.status:type_name -> common.proto.Status
	9,  // 36: memory.proto.MemoryService.CreateMemory:input_type -> memory.proto.CreateMemoryRequest
	11, // 37: memory.proto.MemoryService.GetMemory:input_type -> memory.proto.GetMemoryRequest
	13, // 38: memory.proto.MemoryService.UpdateMemory:input_type -> memory.proto.UpdateMemoryRequest
	15, // 39: memory.proto.MemoryService.DeleteMemory:input_type -> memory.proto.DeleteMemoryRequest
	18, // 40: memory.proto.MemoryService.QueryMemories:input_type -> memory.proto.QueryMemoriesRequest
	20, // 41: memory.proto.MemoryService.SearchMemories:input_type -> memory.proto.SearchMemoriesRequest
	23, // 42: memory.proto.MemoryService.GetRelations:input_type -> memory.proto.GetRelationsRequest
	25, // 43: memory.proto.MemoryService.CreateRelation:input_type -> memory.proto.CreateRelationRequest
	10, // 44: memory.proto.MemoryService.CreateMemory:output_type -> memory.proto.CreateMemoryResponse
	12, // 45: memory.proto.MemoryService.GetMemory:output_type -> memory.proto.GetMemoryResponse
	14, // 46: memory.proto.MemoryService.UpdateMemory:output_type -> memory.proto.UpdateMemoryResponse
	16, // 47: memory.proto.MemoryService.DeleteMemory:output_type -> memory.proto.DeleteMemoryResponse
	19, // 48: memory.proto.MemoryService.QueryMemories:output_type -> memory.proto.QueryMemoriesResponse
	22, // 49: memory.proto.MemoryService.SearchMemories:output_type -> memory.proto.SearchMemoriesResponse
	24, // 50: memory.proto.MemoryService.GetRelations:output_type -> memory.proto.GetRelationsResponse
	26, // 51: memory.proto.MemoryService.CreateRelation:output_type -> memory.proto.CreateRelationResponse
	44, // [44:52] is the sub-list for method output_type
	36, // [36:44] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_memory_proto_init() }
func file_memory_proto_init() {
	if File_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_proto_goTypes,
		DependencyIndexes: file_memory_proto_depIdxs,
		EnumInfos:         file_memory_proto_enumTypes,
		MessageInfos:      file_memory_proto_msgTypes,
	}.Build()
	File_memory_proto = out.File
	file_memory_proto_goTypes = nil
	file_memory_proto_depIdxs = nil
}
