// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: memory.proto

package memorypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	commonpb "github.com/milvus-io/milvus/pkg/v2/proto/commonpb"
)

// MemoryType 记忆类型
type MemoryType int32

const (
	MEMORY_UNKNOWN MemoryType = 0
	EPISODIC       MemoryType = 1
	SEMANTIC       MemoryType = 2
	PROCEDURAL     MemoryType = 3
	SOCIAL         MemoryType = 4
	REFLECTIVE     MemoryType = 5
)

// MemoryLevel 记忆蒸馏层级
type MemoryLevel int32

const (
	LEVEL_UNKNOWN MemoryLevel = 0
	LEVEL_RAW     MemoryLevel = 1
	LEVEL_SUMMARY MemoryLevel = 2
	LEVEL_PATTERN MemoryLevel = 3
)

// MemoryState 记忆状态
type MemoryState int32

const (
	MEMORY_STATE_UNKNOWN MemoryState = 0
	MEMORY_ACTIVE        MemoryState = 1
	MEMORY_FADING        MemoryState = 2
	MEMORY_ARCHIVED      MemoryState = 3
	MEMORY_QUARANTINED   MemoryState = 4
	MEMORY_DELETED       MemoryState = 5
)

// Memory 记忆对象
type Memory struct {
	MemoryID       string            `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	MemoryType     MemoryType        `protobuf:"varint,2,opt,name=memory_type,json=memoryType,proto3,enum=memory.proto.MemoryType" json:"memory_type,omitempty"`
	AgentID        string            `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionID      string            `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope          string            `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Level          MemoryLevel       `protobuf:"varint,6,opt,name=level,proto3,enum=memory.proto.MemoryLevel" json:"level,omitempty"`
	Content        string            `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Summary        string            `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	SourceEventIDs []string          `protobuf:"bytes,9,rep,name=source_event_ids,json=sourceEventIds,proto3" json:"source_event_ids,omitempty"`
	Confidence     float32           `protobuf:"fixed32,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Importance     float32           `protobuf:"fixed32,11,opt,name=importance,proto3" json:"importance,omitempty"`
	FreshnessScore float32           `protobuf:"fixed32,12,opt,name=freshness_score,json=freshnessScore,proto3" json:"freshness_score,omitempty"`
	TTL            int64             `protobuf:"varint,13,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ValidFrom      uint64            `protobuf:"varint,14,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo        uint64            `protobuf:"varint,15,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	ProvenanceRef  string            `protobuf:"bytes,16,opt,name=provenance_ref,json=provenanceRef,proto3" json:"provenance_ref,omitempty"`
	Version        int64             `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	IsActive       bool              `protobuf:"varint,18,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	State          MemoryState       `protobuf:"varint,19,opt,name=state,proto3,enum=memory.proto.MemoryState" json:"state,omitempty"`
	CreatedTs      uint64            `protobuf:"varint,20,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs      uint64            `protobuf:"varint,21,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,22,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EmbeddingRef   string            `protobuf:"bytes,23,opt,name=embedding_ref,json=embeddingRef,proto3" json:"embedding_ref,omitempty"`
	EmbeddingVector []float32        `protobuf:"fixed32,24,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"`
}

func (x *Memory) Reset() { *x = Memory{} }
func (x *Memory) String() string { return "Memory" }
func (*Memory) ProtoMessage() {}

func (x *Memory) GetMemoryID() string { if x != nil { return x.MemoryID }; return "" }
func (x *Memory) GetMemoryType() MemoryType { if x != nil { return x.MemoryType }; return MEMORY_UNKNOWN }
func (x *Memory) GetAgentID() string { if x != nil { return x.AgentID }; return "" }
func (x *Memory) GetSessionID() string { if x != nil { return x.SessionID }; return "" }
func (x *Memory) GetScope() string { if x != nil { return x.Scope }; return "" }
func (x *Memory) GetLevel() MemoryLevel { if x != nil { return x.Level }; return LEVEL_UNKNOWN }
func (x *Memory) GetContent() string { if x != nil { return x.Content }; return "" }
func (x *Memory) GetSummary() string { if x != nil { return x.Summary }; return "" }
func (x *Memory) GetSourceEventIDs() []string { if x != nil { return x.SourceEventIDs }; return nil }
func (x *Memory) GetConfidence() float32 { if x != nil { return x.Confidence }; return 0 }
func (x *Memory) GetImportance() float32 { if x != nil { return x.Importance }; return 0 }
func (x *Memory) GetFreshnessScore() float32 { if x != nil { return x.FreshnessScore }; return 0 }
func (x *Memory) GetTTL() int64 { if x != nil { return x.TTL }; return 0 }
func (x *Memory) GetValidFrom() uint64 { if x != nil { return x.ValidFrom }; return 0 }
func (x *Memory) GetValidTo() uint64 { if x != nil { return x.ValidTo }; return 0 }
func (x *Memory) GetProvenanceRef() string { if x != nil { return x.ProvenanceRef }; return "" }
func (x *Memory) GetVersion() int64 { if x != nil { return x.Version }; return 0 }
func (x *Memory) GetIsActive() bool { if x != nil { return x.IsActive }; return false }
func (x *Memory) GetState() MemoryState { if x != nil { return x.State }; return MEMORY_STATE_UNKNOWN }
func (x *Memory) GetCreatedTs() uint64 { if x != nil { return x.CreatedTs }; return 0 }
func (x *Memory) GetUpdatedTs() uint64 { if x != nil { return x.UpdatedTs }; return 0 }
func (x *Memory) GetMetadata() map[string]string { if x != nil { return x.Metadata }; return nil }
func (x *Memory) GetEmbeddingRef() string { if x != nil { return x.EmbeddingRef }; return "" }
func (x *Memory) GetEmbeddingVector() []float32 { if x != nil { return x.EmbeddingVector }; return nil }

// MemoryPolicy 记忆策略
type MemoryPolicy struct {
	MemoryID         string   `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	SalienceWeight   float32  `protobuf:"fixed32,2,opt,name=salience_weight,json=salienceWeight,proto3" json:"salience_weight,omitempty"`
	TTL              int64    `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DecayFn          string   `protobuf:"bytes,4,opt,name=decay_fn,json=decayFn,proto3" json:"decay_fn,omitempty"`
	Confidence       float32  `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Verified         bool     `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	VerifiedBy       string   `protobuf:"bytes,7,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	VerifiedAt       uint64   `protobuf:"varint,8,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	Quarantined      bool     `protobuf:"varint,9,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	QuarantineReason string   `protobuf:"bytes,10,opt,name=quarantine_reason,json=quarantineReason,proto3" json:"quarantine_reason,omitempty"`
	VisibilityPolicy string   `protobuf:"bytes,11,opt,name=visibility_policy,json=visibilityPolicy,proto3" json:"visibility_policy,omitempty"`
	ReadACL          []string `protobuf:"bytes,12,rep,name=read_acl,json=readAcl,proto3" json:"read_acl,omitempty"`
	WriteACL         []string `protobuf:"bytes,13,rep,name=write_acl,json=writeAcl,proto3" json:"write_acl,omitempty"`
	DeriveACL        []string `protobuf:"bytes,14,rep,name=derive_acl,json=deriveAcl,proto3" json:"derive_acl,omitempty"`
	PolicyReason     string   `protobuf:"bytes,15,opt,name=policy_reason,json=policyReason,proto3" json:"policy_reason,omitempty"`
	PolicySource     string   `protobuf:"bytes,16,opt,name=policy_source,json=policySource,proto3" json:"policy_source,omitempty"`
	PolicyEventID    string   `protobuf:"bytes,17,opt,name=policy_event_id,json=policyEventId,proto3" json:"policy_event_id,omitempty"`
	CreatedTs        uint64   `protobuf:"varint,18,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs        uint64   `protobuf:"varint,19,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
}

func (x *MemoryPolicy) Reset() { *x = MemoryPolicy{} }
func (x *MemoryPolicy) String() string { return "MemoryPolicy" }
func (*MemoryPolicy) ProtoMessage() {}

func (x *MemoryPolicy) GetMemoryID() string { if x != nil { return x.MemoryID }; return "" }
func (x *MemoryPolicy) GetSalienceWeight() float32 { if x != nil { return x.SalienceWeight }; return 0 }
func (x *MemoryPolicy) GetTTL() int64 { if x != nil { return x.TTL }; return 0 }
func (x *MemoryPolicy) GetDecayFn() string { if x != nil { return x.DecayFn }; return "" }
func (x *MemoryPolicy) GetConfidence() float32 { if x != nil { return x.Confidence }; return 0 }
func (x *MemoryPolicy) GetVerified() bool { if x != nil { return x.Verified }; return false }
func (x *MemoryPolicy) GetVerifiedBy() string { if x != nil { return x.VerifiedBy }; return "" }
func (x *MemoryPolicy) GetVerifiedAt() uint64 { if x != nil { return x.VerifiedAt }; return 0 }
func (x *MemoryPolicy) GetQuarantined() bool { if x != nil { return x.Quarantined }; return false }
func (x *MemoryPolicy) GetQuarantineReason() string { if x != nil { return x.QuarantineReason }; return "" }
func (x *MemoryPolicy) GetVisibilityPolicy() string { if x != nil { return x.VisibilityPolicy }; return "" }
func (x *MemoryPolicy) GetReadACL() []string { if x != nil { return x.ReadACL }; return nil }
func (x *MemoryPolicy) GetWriteACL() []string { if x != nil { return x.WriteACL }; return nil }
func (x *MemoryPolicy) GetDeriveACL() []string { if x != nil { return x.DeriveACL }; return nil }
func (x *MemoryPolicy) GetPolicyReason() string { if x != nil { return x.PolicyReason }; return "" }
func (x *MemoryPolicy) GetPolicySource() string { if x != nil { return x.PolicySource }; return "" }
func (x *MemoryPolicy) GetPolicyEventID() string { if x != nil { return x.PolicyEventID }; return "" }
func (x *MemoryPolicy) GetCreatedTs() uint64 { if x != nil { return x.CreatedTs }; return 0 }
func (x *MemoryPolicy) GetUpdatedTs() uint64 { if x != nil { return x.UpdatedTs }; return 0 }

// MemoryAdaptation 记忆适配
type MemoryAdaptation struct {
	MemoryID             map[string]float32 `protobuf:"bytes,2,rep,name=retrieval_profile,json=retrievalProfile,proto3" json:"retrieval_profile,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	RetrievalProfile     map[string]float32 `protobuf:"bytes,3,rep,name=ranking_params,json=rankingParams,proto3" json:"ranking_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	RankingParams        map[string]float32 `protobuf:"bytes,4,rep,name=filtering_thresholds,json=filteringThresholds,proto3" json:"filtering_thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	FilteringThresholds  map[string]float32 `protobuf:"bytes,5,rep,name=projection_weights,json=projectionWeights,proto3" json:"projection_weights,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	ProjectionWeights    string             `protobuf:"bytes,6,opt,name=embedding_family,json=embeddingFamily,proto3" json:"embedding_family,omitempty"`
	EmbeddingFamily      string             `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelID              string             `protobuf:"bytes,8,opt,name=adaptation_reason,json=adaptationReason,proto3" json:"adaptation_reason,omitempty"`
	AdaptationReason     string             `protobuf:"bytes,9,opt,name=adaptation_source,json=adaptationSource,proto3" json:"adaptation_source,omitempty"`
	AdaptationSource     uint64             `protobuf:"varint,10,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	CreatedTs            uint64             `protobuf:"varint,11,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	UpdatedTs            string             `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
}

func (x *MemoryAdaptation) Reset() { *x = MemoryAdaptation{} }
func (x *MemoryAdaptation) String() string { return "MemoryAdaptation" }
func (*MemoryAdaptation) ProtoMessage() {}

// State 状态对象
type State struct {
	StateID            string            `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	AgentID            string            `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionID          string            `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StateType          string            `protobuf:"bytes,4,opt,name=state_type,json=stateType,proto3" json:"state_type,omitempty"`
	StateKey           string            `protobuf:"bytes,5,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	StateValue         []byte            `protobuf:"bytes,6,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	Version            int64             `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	DerivedFromEventID string            `protobuf:"bytes,8,opt,name=derived_from_event_id,json=derivedFromEventId,proto3" json:"derived_from_event_id,omitempty"`
	CheckpointTs       uint64            `protobuf:"varint,9,opt,name=checkpoint_ts,json=checkpointTs,proto3" json:"checkpoint_ts,omitempty"`
	CreatedTs          uint64            `protobuf:"varint,10,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs          uint64            `protobuf:"varint,11,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	Metadata           map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *State) Reset() { *x = State{} }
func (x *State) String() string { return "State" }
func (*State) ProtoMessage() {}

func (x *State) GetStateID() string { if x != nil { return x.StateID }; return "" }
func (x *State) GetAgentID() string { if x != nil { return x.AgentID }; return "" }
func (x *State) GetSessionID() string { if x != nil { return x.SessionID }; return "" }
func (x *State) GetStateType() string { if x != nil { return x.StateType }; return "" }
func (x *State) GetStateKey() string { if x != nil { return x.StateKey }; return "" }
func (x *State) GetStateValue() []byte { if x != nil { return x.StateValue }; return nil }
func (x *State) GetVersion() int64 { if x != nil { return x.Version }; return 0 }
func (x *State) GetDerivedFromEventID() string { if x != nil { return x.DerivedFromEventID }; return "" }
func (x *State) GetCheckpointTs() uint64 { if x != nil { return x.CheckpointTs }; return 0 }
func (x *State) GetCreatedTs() uint64 { if x != nil { return x.CreatedTs }; return 0 }
func (x *State) GetUpdatedTs() uint64 { if x != nil { return x.UpdatedTs }; return 0 }
func (x *State) GetMetadata() map[string]string { if x != nil { return x.Metadata }; return nil }

// Artifact 外部工件
type Artifact struct {
	ArtifactID       string            `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	SessionID        string            `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OwnerAgentID     string            `protobuf:"bytes,3,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	ArtifactType     string            `protobuf:"bytes,4,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	URI              string            `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	ContentRef       string            `protobuf:"bytes,6,opt,name=content_ref,json=contentRef,proto3" json:"content_ref,omitempty"`
	MimeType         string            `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Metadata         map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Hash             string            `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	ProducedByEventID string           `protobuf:"bytes,10,opt,name=produced_by_event_id,json=producedByEventId,proto3" json:"produced_by_event_id,omitempty"`
	Version          int64             `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedTs        uint64            `protobuf:"varint,12,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
}

func (x *Artifact) Reset() { *x = Artifact{} }
func (x *Artifact) String() string { return "Artifact" }
func (*Artifact) ProtoMessage() {}

func (x *Artifact) GetArtifactID() string { if x != nil { return x.ArtifactID }; return "" }
func (x *Artifact) GetSessionID() string { if x != nil { return x.SessionID }; return "" }
func (x *Artifact) GetOwnerAgentID() string { if x != nil { return x.OwnerAgentID }; return "" }
func (x *Artifact) GetArtifactType() string { if x != nil { return x.ArtifactType }; return "" }
func (x *Artifact) GetURI() string { if x != nil { return x.URI }; return "" }
func (x *Artifact) GetContentRef() string { if x != nil { return x.ContentRef }; return "" }
func (x *Artifact) GetMimeType() string { if x != nil { return x.MimeType }; return "" }
func (x *Artifact) GetMetadata() map[string]string { if x != nil { return x.Metadata }; return nil }
func (x *Artifact) GetHash() string { if x != nil { return x.Hash }; return "" }
func (x *Artifact) GetProducedByEventID() string { if x != nil { return x.ProducedByEventID }; return "" }
func (x *Artifact) GetVersion() int64 { if x != nil { return x.Version }; return 0 }
func (x *Artifact) GetCreatedTs() uint64 { if x != nil { return x.CreatedTs }; return 0 }

// Relation 关系/边
type Relation struct {
	EdgeID         string            `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SrcObjectID    string            `protobuf:"bytes,2,opt,name=src_object_id,json=srcObjectId,proto3" json:"src_object_id,omitempty"`
	SrcType        string            `protobuf:"bytes,3,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	DstObjectID    string            `protobuf:"bytes,4,opt,name=dst_object_id,json=dstObjectId,proto3" json:"dst_object_id,omitempty"`
	DstType        string            `protobuf:"bytes,5,opt,name=dst_type,json=dstType,proto3" json:"dst_type,omitempty"`
	RelationType   string            `protobuf:"bytes,6,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Weight         float32           `protobuf:"fixed32,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Properties     map[string]string `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedTs      uint64            `protobuf:"varint,9,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	CreatedByEventID string          `protobuf:"bytes,10,opt,name=created_by_event_id,json=createdByEventId,proto3" json:"created_by_event_id,omitempty"`
}

func (x *Relation) Reset() { *x = Relation{} }
func (x *Relation) String() string { return "Relation" }
func (*Relation) ProtoMessage() {}

func (x *Relation) GetEdgeID() string { if x != nil { return x.EdgeID }; return "" }
func (x *Relation) GetSrcObjectID() string { if x != nil { return x.SrcObjectID }; return "" }
func (x *Relation) GetSrcType() string { if x != nil { return x.SrcType }; return "" }
func (x *Relation) GetDstObjectID() string { if x != nil { return x.DstObjectID }; return "" }
func (x *Relation) GetDstType() string { if x != nil { return x.DstType }; return "" }
func (x *Relation) GetRelationType() string { if x != nil { return x.RelationType }; return "" }
func (x *Relation) GetWeight() float32 { if x != nil { return x.Weight }; return 0 }
func (x *Relation) GetProperties() map[string]string { if x != nil { return x.Properties }; return nil }
func (x *Relation) GetCreatedTs() uint64 { if x != nil { return x.CreatedTs }; return 0 }
func (x *Relation) GetCreatedByEventID() string { if x != nil { return x.CreatedByEventID }; return "" }

// CreateMemoryRequest 创建记忆请求
type CreateMemoryRequest struct {
	TenantID        string            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceID     string            `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentID         string            `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionID       string            `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MemoryType      MemoryType        `protobuf:"varint,5,opt,name=memory_type,json=memoryType,proto3,enum=memory.proto.MemoryType" json:"memory_type,omitempty"`
	Scope           string            `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Content         string            `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Summary         string            `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	SourceEventIDs  []string          `protobuf:"bytes,9,rep,name=source_event_ids,json=sourceEventIds,proto3" json:"source_event_ids,omitempty"`
	Confidence      float32           `protobuf:"fixed32,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Importance      float32           `protobuf:"fixed32,11,opt,name=importance,proto3" json:"importance,omitempty"`
	TTL             int64             `protobuf:"varint,12,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Metadata        map[string]string `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EmbeddingVector []float32         `protobuf:"fixed32,14,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"`
}

func (x *CreateMemoryRequest) Reset() { *x = CreateMemoryRequest{} }
func (x *CreateMemoryRequest) String() string { return "CreateMemoryRequest" }
func (*CreateMemoryRequest) ProtoMessage() {}

func (x *CreateMemoryRequest) GetTenantID() string { if x != nil { return x.TenantID }; return "" }
func (x *CreateMemoryRequest) GetWorkspaceID() string { if x != nil { return x.WorkspaceID }; return "" }
func (x *CreateMemoryRequest) GetAgentID() string { if x != nil { return x.AgentID }; return "" }
func (x *CreateMemoryRequest) GetSessionID() string { if x != nil { return x.SessionID }; return "" }
func (x *CreateMemoryRequest) GetMemoryType() MemoryType { if x != nil { return x.MemoryType }; return MEMORY_UNKNOWN }
func (x *CreateMemoryRequest) GetScope() string { if x != nil { return x.Scope }; return "" }
func (x *CreateMemoryRequest) GetContent() string { if x != nil { return x.Content }; return "" }
func (x *CreateMemoryRequest) GetSummary() string { if x != nil { return x.Summary }; return "" }
func (x *CreateMemoryRequest) GetSourceEventIDs() []string { if x != nil { return x.SourceEventIDs }; return nil }
func (x *CreateMemoryRequest) GetConfidence() float32 { if x != nil { return x.Confidence }; return 0 }
func (x *CreateMemoryRequest) GetImportance() float32 { if x != nil { return x.Importance }; return 0 }
func (x *CreateMemoryRequest) GetTTL() int64 { if x != nil { return x.TTL }; return 0 }
func (x *CreateMemoryRequest) GetMetadata() map[string]string { if x != nil { return x.Metadata }; return nil }
func (x *CreateMemoryRequest) GetEmbeddingVector() []float32 { if x != nil { return x.EmbeddingVector }; return nil }

// CreateMemoryResponse 创建记忆响应
type CreateMemoryResponse struct {
	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MemoryID string          `protobuf:"bytes,2,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Version uint64           `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *CreateMemoryResponse) Reset() { *x = CreateMemoryResponse{} }
func (x *CreateMemoryResponse) String() string { return "CreateMemoryResponse" }
func (*CreateMemoryResponse) ProtoMessage() {}

func (x *CreateMemoryResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *CreateMemoryResponse) GetMemoryID() string { if x != nil { return x.MemoryID }; return "" }
func (x *CreateMemoryResponse) GetVersion() uint64 { if x != nil { return x.Version }; return 0 }

// GetMemoryRequest 获取记忆请求
type GetMemoryRequest struct {
	MemoryID  string `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Version   uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetMemoryRequest) Reset() { *x = GetMemoryRequest{} }
func (x *GetMemoryRequest) String() string { return "GetMemoryRequest" }
func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) GetMemoryID() string { if x != nil { return x.MemoryID }; return "" }
func (x *GetMemoryRequest) GetVersion() uint64 { if x != nil { return x.Version }; return 0 }
func (x *GetMemoryRequest) GetTimestamp() uint64 { if x != nil { return x.Timestamp }; return 0 }

// GetMemoryResponse 获取记忆响应
type GetMemoryResponse struct {
	Status     *commonpb.Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Memory     *Memory           `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Policy     *MemoryPolicy     `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Adaptation *MemoryAdaptation `protobuf:"bytes,4,opt,name=adaptation,proto3" json:"adaptation,omitempty"`
}

func (x *GetMemoryResponse) Reset() { *x = GetMemoryResponse{} }
func (x *GetMemoryResponse) String() string { return "GetMemoryResponse" }
func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *GetMemoryResponse) GetMemory() *Memory { if x != nil { return x.Memory }; return nil }
func (x *GetMemoryResponse) GetPolicy() *MemoryPolicy { if x != nil { return x.Policy }; return nil }
func (x *GetMemoryResponse) GetAdaptation() *MemoryAdaptation { if x != nil { return x.Adaptation }; return nil }

// UpdateMemoryRequest 更新记忆请求
type UpdateMemoryRequest struct {
	MemoryID        string    `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Content         string    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Summary         string    `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Confidence      float32   `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Importance      float32   `protobuf:"fixed32,5,opt,name=importance,proto3" json:"importance,omitempty"`
	TTL             int64     `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Metadata        map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EmbeddingVector []float32 `protobuf:"fixed32,8,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"`
}

func (x *UpdateMemoryRequest) Reset() { *x = UpdateMemoryRequest{} }
func (x *UpdateMemoryRequest) String() string { return "UpdateMemoryRequest" }
func (*UpdateMemoryRequest) ProtoMessage() {}

func (x *UpdateMemoryRequest) GetMemoryID() string { if x != nil { return x.MemoryID }; return "" }
func (x *UpdateMemoryRequest) GetContent() string { if x != nil { return x.Content }; return "" }
func (x *UpdateMemoryRequest) GetSummary() string { if x != nil { return x.Summary }; return "" }
func (x *UpdateMemoryRequest) GetConfidence() float32 { if x != nil { return x.Confidence }; return 0 }
func (x *UpdateMemoryRequest) GetImportance() float32 { if x != nil { return x.Importance }; return 0 }
func (x *UpdateMemoryRequest) GetTTL() int64 { if x != nil { return x.TTL }; return 0 }
func (x *UpdateMemoryRequest) GetMetadata() map[string]string { if x != nil { return x.Metadata }; return nil }
func (x *UpdateMemoryRequest) GetEmbeddingVector() []float32 { if x != nil { return x.EmbeddingVector }; return nil }

// UpdateMemoryResponse 更新记忆响应
type UpdateMemoryResponse struct {
	Status     *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NewVersion uint64           `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
}

func (x *UpdateMemoryResponse) Reset() { *x = UpdateMemoryResponse{} }
func (x *UpdateMemoryResponse) String() string { return "UpdateMemoryResponse" }
func (*UpdateMemoryResponse) ProtoMessage() {}

func (x *UpdateMemoryResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *UpdateMemoryResponse) GetNewVersion() uint64 { if x != nil { return x.NewVersion }; return 0 }

// DeleteMemoryRequest 删除记忆请求
type DeleteMemoryRequest struct {
	MemoryID   string `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	HardDelete bool   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"`
}

func (x *DeleteMemoryRequest) Reset() { *x = DeleteMemoryRequest{} }
func (x *DeleteMemoryRequest) String() string { return "DeleteMemoryRequest" }
func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) GetMemoryID() string { if x != nil { return x.MemoryID }; return "" }
func (x *DeleteMemoryRequest) GetHardDelete() bool { if x != nil { return x.HardDelete }; return false }

// DeleteMemoryResponse 删除记忆响应
type DeleteMemoryResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteMemoryResponse) Reset() { *x = DeleteMemoryResponse{} }
func (x *DeleteMemoryResponse) String() string { return "DeleteMemoryResponse" }
func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }

// MemoryFilter 记忆过滤条件
type MemoryFilter struct {
	AgentIDs       []string      `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	SessionIDs     []string      `protobuf:"bytes,2,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	MemoryTypes    []MemoryType  `protobuf:"varint,3,rep,packed,name=memory_types,json=memoryTypes,proto3,enum=memory.proto.MemoryType" json:"memory_types,omitempty"`
	Levels         []MemoryLevel `protobuf:"varint,4,rep,packed,name=levels,proto3,enum=memory.proto.MemoryLevel" json:"levels,omitempty"`
	States         []MemoryState `protobuf:"varint,5,rep,packed,name=states,proto3,enum=memory.proto.MemoryState" json:"states,omitempty"`
	Scope          string        `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	StartTime      uint64        `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        uint64        `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinConfidence  float32       `protobuf:"fixed32,9,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	MinImportance  float32       `protobuf:"fixed32,10,opt,name=min_importance,json=minImportance,proto3" json:"min_importance,omitempty"`
	MetadataFilter map[string]string `protobuf:"bytes,11,rep,name=metadata_filter,json=metadataFilter,proto3" json:"metadata_filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MemoryFilter) Reset() { *x = MemoryFilter{} }
func (x *MemoryFilter) String() string { return "MemoryFilter" }
func (*MemoryFilter) ProtoMessage() {}

func (x *MemoryFilter) GetAgentIDs() []string { if x != nil { return x.AgentIDs }; return nil }
func (x *MemoryFilter) GetSessionIDs() []string { if x != nil { return x.SessionIDs }; return nil }
func (x *MemoryFilter) GetMemoryTypes() []MemoryType { if x != nil { return x.MemoryTypes }; return nil }
func (x *MemoryFilter) GetLevels() []MemoryLevel { if x != nil { return x.Levels }; return nil }
func (x *MemoryFilter) GetStates() []MemoryState { if x != nil { return x.States }; return nil }
func (x *MemoryFilter) GetScope() string { if x != nil { return x.Scope }; return "" }
func (x *MemoryFilter) GetStartTime() uint64 { if x != nil { return x.StartTime }; return 0 }
func (x *MemoryFilter) GetEndTime() uint64 { if x != nil { return x.EndTime }; return 0 }
func (x *MemoryFilter) GetMinConfidence() float32 { if x != nil { return x.MinConfidence }; return 0 }
func (x *MemoryFilter) GetMinImportance() float32 { if x != nil { return x.MinImportance }; return 0 }
func (x *MemoryFilter) GetMetadataFilter() map[string]string { if x != nil { return x.MetadataFilter }; return nil }

// QueryMemoriesRequest 查询记忆请求
type QueryMemoriesRequest struct {
	Filter    *MemoryFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit     int64         `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset    int64         `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy   string        `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Ascending bool          `protobuf:"varint,5,opt,name=ascending,proto3" json:"ascending,omitempty"`
}

func (x *QueryMemoriesRequest) Reset() { *x = QueryMemoriesRequest{} }
func (x *QueryMemoriesRequest) String() string { return "QueryMemoriesRequest" }
func (*QueryMemoriesRequest) ProtoMessage() {}

func (x *QueryMemoriesRequest) GetFilter() *MemoryFilter { if x != nil { return x.Filter }; return nil }
func (x *QueryMemoriesRequest) GetLimit() int64 { if x != nil { return x.Limit }; return 0 }
func (x *QueryMemoriesRequest) GetOffset() int64 { if x != nil { return x.Offset }; return 0 }
func (x *QueryMemoriesRequest) GetOrderBy() string { if x != nil { return x.OrderBy }; return "" }
func (x *QueryMemoriesRequest) GetAscending() bool { if x != nil { return x.Ascending }; return false }

// QueryMemoriesResponse 查询记忆响应
type QueryMemoriesResponse struct {
	Status     *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Memories   []*Memory        `protobuf:"bytes,2,rep,name=memories,proto3" json:"memories,omitempty"`
	TotalCount int64            `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *QueryMemoriesResponse) Reset() { *x = QueryMemoriesResponse{} }
func (x *QueryMemoriesResponse) String() string { return "QueryMemoriesResponse" }
func (*QueryMemoriesResponse) ProtoMessage() {}

func (x *QueryMemoriesResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *QueryMemoriesResponse) GetMemories() []*Memory { if x != nil { return x.Memories }; return nil }
func (x *QueryMemoriesResponse) GetTotalCount() int64 { if x != nil { return x.TotalCount }; return 0 }

// SearchMemoriesRequest 向量搜索记忆请求
type SearchMemoriesRequest struct {
	TenantID    string        `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceID string        `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	QueryVector []float32     `protobuf:"fixed32,3,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK        int64         `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter      *MemoryFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	MinScore    float32       `protobuf:"fixed32,6,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
}

func (x *SearchMemoriesRequest) Reset() { *x = SearchMemoriesRequest{} }
func (x *SearchMemoriesRequest) String() string { return "SearchMemoriesRequest" }
func (*SearchMemoriesRequest) ProtoMessage() {}

func (x *SearchMemoriesRequest) GetTenantID() string { if x != nil { return x.TenantID }; return "" }
func (x *SearchMemoriesRequest) GetWorkspaceID() string { if x != nil { return x.WorkspaceID }; return "" }
func (x *SearchMemoriesRequest) GetQueryVector() []float32 { if x != nil { return x.QueryVector }; return nil }
func (x *SearchMemoriesRequest) GetTopK() int64 { if x != nil { return x.TopK }; return 0 }
func (x *SearchMemoriesRequest) GetFilter() *MemoryFilter { if x != nil { return x.Filter }; return nil }
func (x *SearchMemoriesRequest) GetMinScore() float32 { if x != nil { return x.MinScore }; return 0 }

// SearchResult 搜索结果
type SearchResult struct {
	Memory      *Memory `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Score       float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Explanation string  `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *SearchResult) Reset() { *x = SearchResult{} }
func (x *SearchResult) String() string { return "SearchResult" }
func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) GetMemory() *Memory { if x != nil { return x.Memory }; return nil }
func (x *SearchResult) GetScore() float32 { if x != nil { return x.Score }; return 0 }
func (x *SearchResult) GetExplanation() string { if x != nil { return x.Explanation }; return "" }

// SearchMemoriesResponse 向量搜索记忆响应
type SearchMemoriesResponse struct {
	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results []*SearchResult  `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchMemoriesResponse) Reset() { *x = SearchMemoriesResponse{} }
func (x *SearchMemoriesResponse) String() string { return "SearchMemoriesResponse" }
func (*SearchMemoriesResponse) ProtoMessage() {}

func (x *SearchMemoriesResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *SearchMemoriesResponse) GetResults() []*SearchResult { if x != nil { return x.Results }; return nil }

// GetRelationsRequest 获取关系请求
type GetRelationsRequest struct {
	ObjectID     string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectType   string `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	RelationType string `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Hop          int64  `protobuf:"varint,4,opt,name=hop,proto3" json:"hop,omitempty"`
}

func (x *GetRelationsRequest) Reset() { *x = GetRelationsRequest{} }
func (x *GetRelationsRequest) String() string { return "GetRelationsRequest" }
func (*GetRelationsRequest) ProtoMessage() {}

func (x *GetRelationsRequest) GetObjectID() string { if x != nil { return x.ObjectID }; return "" }
func (x *GetRelationsRequest) GetObjectType() string { if x != nil { return x.ObjectType }; return "" }
func (x *GetRelationsRequest) GetRelationType() string { if x != nil { return x.RelationType }; return "" }
func (x *GetRelationsRequest) GetHop() int64 { if x != nil { return x.Hop }; return 0 }

// GetRelationsResponse 获取关系响应
type GetRelationsResponse struct {
	Status    *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Relations []*Relation      `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
}

func (x *GetRelationsResponse) Reset() { *x = GetRelationsResponse{} }
func (x *GetRelationsResponse) String() string { return "GetRelationsResponse" }
func (*GetRelationsResponse) ProtoMessage() {}

func (x *GetRelationsResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *GetRelationsResponse) GetRelations() []*Relation { if x != nil { return x.Relations }; return nil }

// CreateRelationRequest 创建关系请求
type CreateRelationRequest struct {
	SrcObjectID    string            `protobuf:"bytes,1,opt,name=src_object_id,json=srcObjectId,proto3" json:"src_object_id,omitempty"`
	SrcType        string            `protobuf:"bytes,2,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	DstObjectID    string            `protobuf:"bytes,3,opt,name=dst_object_id,json=dstObjectId,proto3" json:"dst_object_id,omitempty"`
	DstType        string            `protobuf:"bytes,4,opt,name=dst_type,json=dstType,proto3" json:"dst_type,omitempty"`
	RelationType   string            `protobuf:"bytes,5,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Weight         float32           `protobuf:"fixed32,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Properties     map[string]string `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedByEventID string          `protobuf:"bytes,8,opt,name=created_by_event_id,json=createdByEventId,proto3" json:"created_by_event_id,omitempty"`
}

func (x *CreateRelationRequest) Reset() { *x = CreateRelationRequest{} }
func (x *CreateRelationRequest) String() string { return "CreateRelationRequest" }
func (*CreateRelationRequest) ProtoMessage() {}

func (x *CreateRelationRequest) GetSrcObjectID() string { if x != nil { return x.SrcObjectID }; return "" }
func (x *CreateRelationRequest) GetSrcType() string { if x != nil { return x.SrcType }; return "" }
func (x *CreateRelationRequest) GetDstObjectID() string { if x != nil { return x.DstObjectID }; return "" }
func (x *CreateRelationRequest) GetDstType() string { if x != nil { return x.DstType }; return "" }
func (x *CreateRelationRequest) GetRelationType() string { if x != nil { return x.RelationType }; return "" }
func (x *CreateRelationRequest) GetWeight() float32 { if x != nil { return x.Weight }; return 0 }
func (x *CreateRelationRequest) GetProperties() map[string]string { if x != nil { return x.Properties }; return nil }
func (x *CreateRelationRequest) GetCreatedByEventID() string { if x != nil { return x.CreatedByEventID }; return "" }

// CreateRelationResponse 创建关系响应
type CreateRelationResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EdgeID string           `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
}

func (x *CreateRelationResponse) Reset() { *x = CreateRelationResponse{} }
func (x *CreateRelationResponse) String() string { return "CreateRelationResponse" }
func (*CreateRelationResponse) ProtoMessage() {}

func (x *CreateRelationResponse) GetStatus() *commonpb.Status { if x != nil { return x.Status }; return nil }
func (x *CreateRelationResponse) GetEdgeID() string { if x != nil { return x.EdgeID }; return "" }

// MemoryServiceClient is the client API for MemoryService service.
type MemoryServiceClient interface {
	CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error)
	GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error)
	UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*UpdateMemoryResponse, error)
	DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error)
	QueryMemories(ctx context.Context, in *QueryMemoriesRequest, opts ...grpc.CallOption) (*QueryMemoriesResponse, error)
	SearchMemories(ctx context.Context, in *SearchMemoriesRequest, opts ...grpc.CallOption) (*SearchMemoriesResponse, error)
	GetRelations(ctx context.Context, in *GetRelationsRequest, opts ...grpc.CallOption) (*GetRelationsResponse, error)
	CreateRelation(ctx context.Context, in *CreateRelationRequest, opts ...grpc.CallOption) (*CreateRelationResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error) {
	out := new(CreateMemoryResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/CreateMemory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error) {
	out := new(GetMemoryResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/GetMemory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*UpdateMemoryResponse, error) {
	out := new(UpdateMemoryResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/UpdateMemory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error) {
	out := new(DeleteMemoryResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/DeleteMemory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) QueryMemories(ctx context.Context, in *QueryMemoriesRequest, opts ...grpc.CallOption) (*QueryMemoriesResponse, error) {
	out := new(QueryMemoriesResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/QueryMemories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SearchMemories(ctx context.Context, in *SearchMemoriesRequest, opts ...grpc.CallOption) (*SearchMemoriesResponse, error) {
	out := new(SearchMemoriesResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/SearchMemories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetRelations(ctx context.Context, in *GetRelationsRequest, opts ...grpc.CallOption) (*GetRelationsResponse, error) {
	out := new(GetRelationsResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/GetRelations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) CreateRelation(ctx context.Context, in *CreateRelationRequest, opts ...grpc.CallOption) (*CreateRelationResponse, error) {
	out := new(CreateRelationResponse)
	err := c.cc.Invoke(ctx, "/memory.proto.MemoryService/CreateRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
type MemoryServiceServer interface {
	CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error)
	GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error)
	UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryResponse, error)
	DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error)
	QueryMemories(context.Context, *QueryMemoriesRequest) (*QueryMemoriesResponse, error)
	SearchMemories(context.Context, *SearchMemoriesRequest) (*SearchMemoriesResponse, error)
	GetRelations(context.Context, *GetRelationsRequest) (*GetRelationsResponse, error)
	CreateRelation(context.Context, *CreateRelationRequest) (*CreateRelationResponse, error)
}

// UnimplementedMemoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMemory not implemented")
}
func (UnimplementedMemoryServiceServer) GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemory not implemented")
}
func (UnimplementedMemoryServiceServer) UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemory not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMemory not implemented")
}
func (UnimplementedMemoryServiceServer) QueryMemories(context.Context, *QueryMemoriesRequest) (*QueryMemoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMemories not implemented")
}
func (UnimplementedMemoryServiceServer) SearchMemories(context.Context, *SearchMemoriesRequest) (*SearchMemoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMemories not implemented")
}
func (UnimplementedMemoryServiceServer) GetRelations(context.Context, *GetRelationsRequest) (*GetRelationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRelations not implemented")
}
func (UnimplementedMemoryServiceServer) CreateRelation(context.Context, *CreateRelationRequest) (*CreateRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRelation not implemented")
}

// RegisterMemoryServiceServer registers the MemoryServiceServer to the grpc.Server.
func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_CreateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).CreateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/CreateMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).CreateMemory(ctx, req.(*CreateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/GetMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetMemory(ctx, req.(*GetMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_UpdateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).UpdateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/UpdateMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).UpdateMemory(ctx, req.(*UpdateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/DeleteMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteMemory(ctx, req.(*DeleteMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_QueryMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).QueryMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/QueryMemories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).QueryMemories(ctx, req.(*QueryMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SearchMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SearchMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/SearchMemories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SearchMemories(ctx, req.(*SearchMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/GetRelations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetRelations(ctx, req.(*GetRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_CreateRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).CreateRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.proto.MemoryService/CreateRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).CreateRelation(ctx, req.(*CreateRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memory.proto.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateMemory", Handler: _MemoryService_CreateMemory_Handler},
		{MethodName: "GetMemory", Handler: _MemoryService_GetMemory_Handler},
		{MethodName: "UpdateMemory", Handler: _MemoryService_UpdateMemory_Handler},
		{MethodName: "DeleteMemory", Handler: _MemoryService_DeleteMemory_Handler},
		{MethodName: "QueryMemories", Handler: _MemoryService_QueryMemories_Handler},
		{MethodName: "SearchMemories", Handler: _MemoryService_SearchMemories_Handler},
		{MethodName: "GetRelations", Handler: _MemoryService_GetRelations_Handler},
		{MethodName: "CreateRelation", Handler: _MemoryService_CreateRelation_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory.proto",
}
