// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: agent.proto

package agentpb

import (
	commonpb "github.com/milvus-io/milvus/pkg/v2/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentState 定义Agent的状态
type AgentState int32

const (
	AgentState_AGENT_UNKNOWN    AgentState = 0
	AgentState_AGENT_CREATING   AgentState = 1
	AgentState_AGENT_ACTIVE     AgentState = 2
	AgentState_AGENT_PAUSED     AgentState = 3
	AgentState_AGENT_TERMINATED AgentState = 4
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_UNKNOWN",
		1: "AGENT_CREATING",
		2: "AGENT_ACTIVE",
		3: "AGENT_PAUSED",
		4: "AGENT_TERMINATED",
	}
	AgentState_value = map[string]int32{
		"AGENT_UNKNOWN":    0,
		"AGENT_CREATING":   1,
		"AGENT_ACTIVE":     2,
		"AGENT_PAUSED":     3,
		"AGENT_TERMINATED": 4,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// SessionState 定义Session的状态
type SessionState int32

const (
	SessionState_SESSION_UNKNOWN   SessionState = 0
	SessionState_SESSION_CREATING  SessionState = 1
	SessionState_SESSION_ACTIVE    SessionState = 2
	SessionState_SESSION_PAUSED    SessionState = 3
	SessionState_SESSION_COMPLETED SessionState = 4
	SessionState_SESSION_FAILED    SessionState = 5
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_UNKNOWN",
		1: "SESSION_CREATING",
		2: "SESSION_ACTIVE",
		3: "SESSION_PAUSED",
		4: "SESSION_COMPLETED",
		5: "SESSION_FAILED",
	}
	SessionState_value = map[string]int32{
		"SESSION_UNKNOWN":   0,
		"SESSION_CREATING":  1,
		"SESSION_ACTIVE":    2,
		"SESSION_PAUSED":    3,
		"SESSION_COMPLETED": 4,
		"SESSION_FAILED":    5,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// Agent 表示执行主体
type AgentInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId         string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentType           string                 `protobuf:"bytes,4,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	RoleProfile         string                 `protobuf:"bytes,5,opt,name=role_profile,json=roleProfile,proto3" json:"role_profile,omitempty"`
	PolicyRef           string                 `protobuf:"bytes,6,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	CapabilitySet       []string               `protobuf:"bytes,7,rep,name=capability_set,json=capabilitySet,proto3" json:"capability_set,omitempty"`
	DefaultMemoryPolicy string                 `protobuf:"bytes,8,opt,name=default_memory_policy,json=defaultMemoryPolicy,proto3" json:"default_memory_policy,omitempty"`
	CreatedTs           uint64                 `protobuf:"varint,9,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs           uint64                 `protobuf:"varint,10,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	State               AgentState             `protobuf:"varint,11,opt,name=state,proto3,enum=agent.proto.AgentState" json:"state,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AgentInfo) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AgentInfo) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentInfo) GetRoleProfile() string {
	if x != nil {
		return x.RoleProfile
	}
	return ""
}

func (x *AgentInfo) GetPolicyRef() string {
	if x != nil {
		return x.PolicyRef
	}
	return ""
}

func (x *AgentInfo) GetCapabilitySet() []string {
	if x != nil {
		return x.CapabilitySet
	}
	return nil
}

func (x *AgentInfo) GetDefaultMemoryPolicy() string {
	if x != nil {
		return x.DefaultMemoryPolicy
	}
	return ""
}

func (x *AgentInfo) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *AgentInfo) GetUpdatedTs() uint64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

func (x *AgentInfo) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_UNKNOWN
}

func (x *AgentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Session 表示具体任务、会话或推理线程
type SessionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentSessionId string                 `protobuf:"bytes,3,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	TaskType        string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Goal            string                 `protobuf:"bytes,5,opt,name=goal,proto3" json:"goal,omitempty"`
	ContextRef      string                 `protobuf:"bytes,6,opt,name=context_ref,json=contextRef,proto3" json:"context_ref,omitempty"`
	StartTs         uint64                 `protobuf:"varint,7,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs           uint64                 `protobuf:"varint,8,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	State           SessionState           `protobuf:"varint,9,opt,name=state,proto3,enum=agent.proto.SessionState" json:"state,omitempty"`
	BudgetToken     int64                  `protobuf:"varint,10,opt,name=budget_token,json=budgetToken,proto3" json:"budget_token,omitempty"`
	BudgetTimeMs    int64                  `protobuf:"varint,11,opt,name=budget_time_ms,json=budgetTimeMs,proto3" json:"budget_time_ms,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionInfo) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *SessionInfo) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *SessionInfo) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *SessionInfo) GetContextRef() string {
	if x != nil {
		return x.ContextRef
	}
	return ""
}

func (x *SessionInfo) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *SessionInfo) GetEndTs() uint64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *SessionInfo) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_UNKNOWN
}

func (x *SessionInfo) GetBudgetToken() int64 {
	if x != nil {
		return x.BudgetToken
	}
	return 0
}

func (x *SessionInfo) GetBudgetTimeMs() int64 {
	if x != nil {
		return x.BudgetTimeMs
	}
	return 0
}

func (x *SessionInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateAgentRequest 创建Agent请求
type CreateAgentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantId            string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId         string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentType           string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	RoleProfile         string                 `protobuf:"bytes,4,opt,name=role_profile,json=roleProfile,proto3" json:"role_profile,omitempty"`
	CapabilitySet       []string               `protobuf:"bytes,5,rep,name=capability_set,json=capabilitySet,proto3" json:"capability_set,omitempty"`
	DefaultMemoryPolicy string                 `protobuf:"bytes,6,opt,name=default_memory_policy,json=defaultMemoryPolicy,proto3" json:"default_memory_policy,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateAgentRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateAgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *CreateAgentRequest) GetRoleProfile() string {
	if x != nil {
		return x.RoleProfile
	}
	return ""
}

func (x *CreateAgentRequest) GetCapabilitySet() []string {
	if x != nil {
		return x.CapabilitySet
	}
	return nil
}

func (x *CreateAgentRequest) GetDefaultMemoryPolicy() string {
	if x != nil {
		return x.DefaultMemoryPolicy
	}
	return ""
}

func (x *CreateAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateAgentResponse 创建Agent响应
type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetAgentRequest 获取Agent请求
type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetAgentResponse 获取Agent响应
type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Agent         *AgentInfo             `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

// ListAgentsRequest 列出Agent请求
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAgentsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListAgentsRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

// ListAgentsResponse 列出Agent响应
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Agents        []*AgentInfo           `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// UpdateAgentRequest 更新Agent请求
type UpdateAgentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RoleProfile         string                 `protobuf:"bytes,2,opt,name=role_profile,json=roleProfile,proto3" json:"role_profile,omitempty"`
	CapabilitySet       []string               `protobuf:"bytes,3,rep,name=capability_set,json=capabilitySet,proto3" json:"capability_set,omitempty"`
	DefaultMemoryPolicy string                 `protobuf:"bytes,4,opt,name=default_memory_policy,json=defaultMemoryPolicy,proto3" json:"default_memory_policy,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentRequest) GetRoleProfile() string {
	if x != nil {
		return x.RoleProfile
	}
	return ""
}

func (x *UpdateAgentRequest) GetCapabilitySet() []string {
	if x != nil {
		return x.CapabilitySet
	}
	return nil
}

func (x *UpdateAgentRequest) GetDefaultMemoryPolicy() string {
	if x != nil {
		return x.DefaultMemoryPolicy
	}
	return ""
}

func (x *UpdateAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateAgentResponse 更新Agent响应
type UpdateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentResponse) Reset() {
	*x = UpdateAgentResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentResponse) ProtoMessage() {}

func (x *UpdateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeleteAgentRequest 删除Agent请求
type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// DeleteAgentResponse 删除Agent响应
type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// CreateSessionRequest 创建Session请求
type CreateSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentSessionId string                 `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	TaskType        string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Goal            string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	ContextRef      string                 `protobuf:"bytes,5,opt,name=context_ref,json=contextRef,proto3" json:"context_ref,omitempty"`
	BudgetToken     int64                  `protobuf:"varint,6,opt,name=budget_token,json=budgetToken,proto3" json:"budget_token,omitempty"`
	BudgetTimeMs    int64                  `protobuf:"varint,7,opt,name=budget_time_ms,json=budgetTimeMs,proto3" json:"budget_time_ms,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSessionRequest) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateSessionRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateSessionRequest) GetContextRef() string {
	if x != nil {
		return x.ContextRef
	}
	return ""
}

func (x *CreateSessionRequest) GetBudgetToken() int64 {
	if x != nil {
		return x.BudgetToken
	}
	return 0
}

func (x *CreateSessionRequest) GetBudgetTimeMs() int64 {
	if x != nil {
		return x.BudgetTimeMs
	}
	return 0
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateSessionResponse 创建Session响应
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSessionResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetSessionRequest 获取Session请求
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetSessionResponse 获取Session响应
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Session       *SessionInfo           `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetSessionResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

// ListSessionsRequest 列出Session请求
type ListSessionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentSessionId string                 `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	State           SessionState           `protobuf:"varint,3,opt,name=state,proto3,enum=agent.proto.SessionState" json:"state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ListSessionsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListSessionsRequest) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *ListSessionsRequest) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_UNKNOWN
}

// ListSessionsResponse 列出Session响应
type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Sessions      []*SessionInfo         `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ListSessionsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// UpdateSessionRequest 更新Session请求
type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         SessionState           `protobuf:"varint,2,opt,name=state,proto3,enum=agent.proto.SessionState" json:"state,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_UNKNOWN
}

func (x *UpdateSessionRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *UpdateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateSessionResponse 更新Session响应
type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateSessionResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\vagent.proto\x1a\fcommon.proto\x1a\x19google/protobuf/any.proto\"\x8e\x04\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x04 \x01(\tR\tagentType\x12!\n" +
	"\frole_profile\x18\x05 \x01(\tR\vroleProfile\x12\x1d\n" +
	"\n" +
	"policy_ref\x18\x06 \x01(\tR\tpolicyRef\x12%\n" +
	"\x0ecapability_set\x18\a \x03(\tR\rcapabilitySet\x122\n" +
	"\x15default_memory_policy\x18\b \x01(\tR\x13defaultMemoryPolicy\x12\x1d\n" +
	"\n" +
	"created_ts\x18\t \x01(\x04R\tcreatedTs\x12\x1d\n" +
	"\n" +
	"updated_ts\x18\n" +
	" \x01(\x04R\tupdatedTs\x12-\n" +
	"\x05state\x18\v \x01(\x0e2\x17.agent.proto.AgentStateR\x05state\x12@\n" +
	"\bmetadata\x18\f \x03(\v2$.agent.proto.AgentInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x03\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x11parent_session_id\x18\x03 \x01(\tR\x0fparentSessionId\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x12\x12\n" +
	"\x04goal\x18\x05 \x01(\tR\x04goal\x12\x1f\n" +
	"\vcontext_ref\x18\x06 \x01(\tR\n" +
	"contextRef\x12\x19\n" +
	"\bstart_ts\x18\a \x01(\x04R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\b \x01(\x04R\x05endTs\x12/\n" +
	"\x05state\x18\t \x01(\x0e2\x19.agent.proto.SessionStateR\x05state\x12!\n" +
	"\fbudget_token\x18\n" +
	" \x01(\x03R\vbudgetToken\x12$\n" +
	"\x0ebudget_time_ms\x18\v \x01(\x03R\fbudgetTimeMs\x12B\n" +
	"\bmetadata\x18\f \x03(\v2&.agent.proto.SessionInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x02\n" +
	"\x12CreateAgentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12!\n" +
	"\frole_profile\x18\x04 \x01(\tR\vroleProfile\x12%\n" +
	"\x0ecapability_set\x18\x05 \x03(\tR\rcapabilitySet\x122\n" +
	"\x15default_memory_policy\x18\x06 \x01(\tR\x13defaultMemoryPolicy\x12I\n" +
	"\bmetadata\x18\a \x03(\v2-.agent.proto.CreateAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x13CreateAgentResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"n\n" +
	"\x10GetAgentResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12,\n" +
	"\x05agent\x18\x02 \x01(\v2\x16.agent.proto.AgentInfoR\x05agent\"r\n" +
	"\x11ListAgentsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\"r\n" +
	"\x12ListAgentsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12.\n" +
	"\x06agents\x18\x02 \x03(\v2\x16.agent.proto.AgentInfoR\x06agents\"\xb5\x02\n" +
	"\x12UpdateAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\frole_profile\x18\x02 \x01(\tR\vroleProfile\x12%\n" +
	"\x0ecapability_set\x18\x03 \x03(\tR\rcapabilitySet\x122\n" +
	"\x15default_memory_policy\x18\x04 \x01(\tR\x13defaultMemoryPolicy\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.agent.proto.UpdateAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x13UpdateAgentResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\"/\n" +
	"\x12DeleteAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"C\n" +
	"\x13DeleteAgentResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\"\x82\x03\n" +
	"\x14CreateSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x11parent_session_id\x18\x02 \x01(\tR\x0fparentSessionId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x1f\n" +
	"\vcontext_ref\x18\x05 \x01(\tR\n" +
	"contextRef\x12!\n" +
	"\fbudget_token\x18\x06 \x01(\x03R\vbudgetToken\x12$\n" +
	"\x0ebudget_time_ms\x18\a \x01(\x03R\fbudgetTimeMs\x12K\n" +
	"\bmetadata\x18\b \x03(\v2/.agent.proto.CreateSessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x15CreateSessionResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"v\n" +
	"\x12GetSessionResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x122\n" +
	"\asession\x18\x02 \x01(\v2\x18.agent.proto.SessionInfoR\asession\"\x8d\x01\n" +
	"\x13ListSessionsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x11parent_session_id\x18\x02 \x01(\tR\x0fparentSessionId\x12/\n" +
	"\x05state\x18\x03 \x01(\x0e2\x19.agent.proto.SessionStateR\x05state\"z\n" +
	"\x14ListSessionsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status\x124\n" +
	"\bsessions\x18\x02 \x03(\v2\x18.agent.proto.SessionInfoR\bsessions\"\x84\x02\n" +
	"\x14UpdateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.agent.proto.SessionStateR\x05state\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.agent.proto.UpdateSessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x15UpdateSessionResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.proto.StatusR\x06status*m\n" +
	"\n" +
	"AgentState\x12\x11\n" +
	"\rAGENT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eAGENT_CREATING\x10\x01\x12\x10\n" +
	"\fAGENT_ACTIVE\x10\x02\x12\x10\n" +
	"\fAGENT_PAUSED\x10\x03\x12\x14\n" +
	"\x10AGENT_TERMINATED\x10\x04*\x8c\x01\n" +
	"\fSessionState\x12\x13\n" +
	"\x0fSESSION_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10SESSION_CREATING\x10\x01\x12\x12\n" +
	"\x0eSESSION_ACTIVE\x10\x02\x12\x12\n" +
	"\x0eSESSION_PAUSED\x10\x03\x12\x15\n" +
	"\x11SESSION_COMPLETED\x10\x04\x12\x12\n" +
	"\x0eSESSION_FAILED\x10\x052\xf0\x05\n" +
	"\fAgentService\x12P\n" +
	"\vCreateAgent\x12\x1f.agent.proto.CreateAgentRequest\x1a .agent.proto.CreateAgentResponse\x12G\n" +
	"\bGetAgent\x12\x1c.agent.proto.GetAgentRequest\x1a\x1d.agent.proto.GetAgentResponse\x12M\n" +
	"\n" +
	"ListAgents\x12\x1e.agent.proto.ListAgentsRequest\x1a\x1f.agent.proto.ListAgentsResponse\x12P\n" +
	"\vUpdateAgent\x12\x1f.agent.proto.UpdateAgentRequest\x1a .agent.proto.UpdateAgentResponse\x12P\n" +
	"\vDeleteAgent\x12\x1f.agent.proto.DeleteAgentRequest\x1a .agent.proto.DeleteAgentResponse\x12V\n" +
	"\rCreateSession\x12!.agent.proto.CreateSessionRequest\x1a\".agent.proto.CreateSessionResponse\x12M\n" +
	"\n" +
	"GetSession\x12\x1e.agent.proto.GetSessionRequest\x1a\x1f.agent.proto.GetSessionResponse\x12S\n" +
	"\fListSessions\x12 .agent.proto.ListSessionsRequest\x1a!.agent.proto.ListSessionsResponse\x12V\n" +
	"\rUpdateSession\x12!.agent.proto.UpdateSessionRequest\x1a\".agent.proto.UpdateSessionResponseB2Z0github.com/milvus-io/milvus/pkg/v2/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_agent_proto_goTypes = []any{
	(AgentState)(0),               // 0: agent.proto.AgentState
	(SessionState)(0),             // 1: agent.proto.SessionState
	(*AgentInfo)(nil),             // 2: agent.proto.AgentInfo
	(*SessionInfo)(nil),           // 3: agent.proto.SessionInfo
	(*CreateAgentRequest)(nil),    // 4: agent.proto.CreateAgentRequest
	(*CreateAgentResponse)(nil),   // 5: agent.proto.CreateAgentResponse
	(*GetAgentRequest)(nil),       // 6: agent.proto.GetAgentRequest
	(*GetAgentResponse)(nil),      // 7: agent.proto.GetAgentResponse
	(*ListAgentsRequest)(nil),     // 8: agent.proto.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 9: agent.proto.ListAgentsResponse
	(*UpdateAgentRequest)(nil),    // 10: agent.proto.UpdateAgentRequest
	(*UpdateAgentResponse)(nil),   // 11: agent.proto.UpdateAgentResponse
	(*DeleteAgentRequest)(nil),    // 12: agent.proto.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),   // 13: agent.proto.DeleteAgentResponse
	(*CreateSessionRequest)(nil),  // 14: agent.proto.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 15: agent.proto.CreateSessionResponse
	(*GetSessionRequest)(nil),     // 16: agent.proto.GetSessionRequest
	(*GetSessionResponse)(nil),    // 17: agent.proto.GetSessionResponse
	(*ListSessionsRequest)(nil),   // 18: agent.proto.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 19: agent.proto.ListSessionsResponse
	(*UpdateSessionRequest)(nil),  // 20: agent.proto.UpdateSessionRequest
	(*UpdateSessionResponse)(nil), // 21: agent.proto.UpdateSessionResponse
	nil,                           // 22: agent.proto.AgentInfo.MetadataEntry
	nil,                           // 23: agent.proto.SessionInfo.MetadataEntry
	nil,                           // 24: agent.proto.CreateAgentRequest.MetadataEntry
	nil,                           // 25: agent.proto.UpdateAgentRequest.MetadataEntry
	nil,                           // 26: agent.proto.CreateSessionRequest.MetadataEntry
	nil,                           // 27: agent.proto.UpdateSessionRequest.MetadataEntry
	(*commonpb.Status)(nil),       // 28: common.proto.Status
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: agent.proto.AgentInfo.state:type_name -> agent.proto.AgentState
	22, // 1: agent.proto.AgentInfo.metadata:type_name -> agent.proto.AgentInfo.MetadataEntry
	1,  // 2: agent.proto.SessionInfo.state:type_name -> agent.proto.SessionState
	23, // 3: agent.proto.SessionInfo.metadata:type_name -> agent.proto.SessionInfo.MetadataEntry
	24, // 4: agent.proto.CreateAgentRequest.metadata:type_name -> agent.proto.CreateAgentRequest.MetadataEntry
	28, // 5: agent.proto.CreateAgentResponse.status:type_name -> common.proto.Status
	28, // 6: agent.proto.GetAgentResponse.status:type_name -> common.proto.Status
	2,  // 7: agent.proto.GetAgentResponse.agent:type_name -> agent.proto.AgentInfo
	28, // 8: agent.proto.ListAgentsResponse.status:type_name -> common.proto.Status
	2,  // 9: agent.proto.ListAgentsResponse.agents:type_name -> agent.proto.AgentInfo
	25, // 10: agent.proto.UpdateAgentRequest.metadata:type_name -> agent.proto.UpdateAgentRequest.MetadataEntry
	28, // 11: agent.proto.UpdateAgentResponse.status:type_name -> common.proto.Status
	28, // 12: agent.proto.DeleteAgentResponse.status:type_name -> common.proto.Status
	26, // 13: agent.proto.CreateSessionRequest.metadata:type_name -> agent.proto.CreateSessionRequest.MetadataEntry
	28, // 14: agent.proto.CreateSessionResponse.status:type_name -> common.proto.Status
	28, // 15: agent.proto.GetSessionResponse.status:type_name -> common.proto.Status
	3,  // 16: agent.proto.GetSessionResponse.session:type_name -> agent.proto.SessionInfo
	1,  // 17: agent.proto.ListSessionsRequest.state:type_name -> agent.proto.SessionState
	28, // 18: agent.proto.ListSessionsResponse.status:type_name -> common.proto.Status
	3,  // 19: agent.proto.ListSessionsResponse.sessions:type_name -> agent.proto.SessionInfo
	1,  // 20: agent.proto.UpdateSessionRequest.state:type_name -> agent.proto.SessionState
	27, // 21: agent.proto.UpdateSessionRequest.metadata:type_name -> agent.proto.UpdateSessionRequest.MetadataEntry
	28, // 22: agent.proto.UpdateSessionResponse.status:type_name -> common.proto.Status
	4,  // 23: agent.proto.AgentService.CreateAgent:input_type -> agent.proto.CreateAgentRequest
	6,  // 24: agent.proto.AgentService.GetAgent:input_type -> agent.proto.GetAgentRequest
	8,  // 25: agent.proto.AgentService.ListAgents:input_type -> agent.proto.ListAgentsRequest
	10, // 26: agent.proto.AgentService.UpdateAgent:input_type -> agent.proto.UpdateAgentRequest
	12, // 27: agent.proto.AgentService.DeleteAgent:input_type -> agent.proto.DeleteAgentRequest
	14, // 28: agent.proto.AgentService.CreateSession:input_type -> agent.proto.CreateSessionRequest
	16, // 29: agent.proto.AgentService.GetSession:input_type -> agent.proto.GetSessionRequest
	18, // 30: agent.proto.AgentService.ListSessions:input_type -> agent.proto.ListSessionsRequest
	20, // 31: agent.proto.AgentService.UpdateSession:input_type -> agent.proto.UpdateSessionRequest
	5,  // 32: agent.proto.AgentService.CreateAgent:output_type -> agent.proto.CreateAgentResponse
	7,  // 33: agent.proto.AgentService.GetAgent:output_type -> agent.proto.GetAgentResponse
	9,  // 34: agent.proto.AgentService.ListAgents:output_type -> agent.proto.ListAgentsResponse
	11, // 35: agent.proto.AgentService.UpdateAgent:output_type -> agent.proto.UpdateAgentResponse
	13, // 36: agent.proto.AgentService.DeleteAgent:output_type -> agent.proto.DeleteAgentResponse
	15, // 37: agent.proto.AgentService.CreateSession:output_type -> agent.proto.CreateSessionResponse
	17, // 38: agent.proto.AgentService.GetSession:output_type -> agent.proto.GetSessionResponse
	19, // 39: agent.proto.AgentService.ListSessions:output_type -> agent.proto.ListSessionsResponse
	21, // 40: agent.proto.AgentService.UpdateSession:output_type -> agent.proto.UpdateSessionResponse
	32, // [32:41] is the sub-list for method output_type
	23, // [23:32] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
