// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	commonpb "github.com/milvus-io/milvus/pkg/v2/proto/commonpb"
)

// AgentState 定义Agent的状态
type AgentState int32

const (
	AGENT_UNKNOWN    AgentState = 0
	AGENT_CREATING   AgentState = 1
	AGENT_ACTIVE     AgentState = 2
	AGENT_PAUSED     AgentState = 3
	AGENT_TERMINATED AgentState = 4
)

// SessionState 定义Session的状态
type SessionState int32

const (
	SESSION_UNKNOWN   SessionState = 0
	SESSION_CREATING  SessionState = 1
	SESSION_ACTIVE    SessionState = 2
	SESSION_PAUSED    SessionState = 3
	SESSION_COMPLETED SessionState = 4
	SESSION_FAILED    SessionState = 5
)

// AgentInfo 表示执行主体
type AgentInfo struct {
	AgentID             string            `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantID            string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceID         string            `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentType           string            `protobuf:"bytes,4,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	RoleProfile         string            `protobuf:"bytes,5,opt,name=role_profile,json=roleProfile,proto3" json:"role_profile,omitempty"`
	PolicyRef           string            `protobuf:"bytes,6,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	CapabilitySet       []string          `protobuf:"bytes,7,rep,name=capability_set,json=capabilitySet,proto3" json:"capability_set,omitempty"`
	DefaultMemoryPolicy string            `protobuf:"bytes,8,opt,name=default_memory_policy,json=defaultMemoryPolicy,proto3" json:"default_memory_policy,omitempty"`
	CreatedTs           uint64            `protobuf:"varint,9,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs           uint64            `protobuf:"varint,10,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	State               AgentState        `protobuf:"varint,11,opt,name=state,proto3,enum=agent.proto.AgentState" json:"state,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
}

func (x *AgentInfo) String() string {
	return "AgentInfo"
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *AgentInfo) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *AgentInfo) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

func (x *AgentInfo) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentInfo) GetRoleProfile() string {
	if x != nil {
		return x.RoleProfile
	}
	return ""
}

func (x *AgentInfo) GetPolicyRef() string {
	if x != nil {
		return x.PolicyRef
	}
	return ""
}

func (x *AgentInfo) GetCapabilitySet() []string {
	if x != nil {
		return x.CapabilitySet
	}
	return nil
}

func (x *AgentInfo) GetDefaultMemoryPolicy() string {
	if x != nil {
		return x.DefaultMemoryPolicy
	}
	return ""
}

func (x *AgentInfo) GetCreatedTs() uint64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *AgentInfo) GetUpdatedTs() uint64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

func (x *AgentInfo) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AGENT_UNKNOWN
}

func (x *AgentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SessionInfo 表示具体任务、会话或推理线程
type SessionInfo struct {
	SessionID       string            `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentID         string            `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentSessionID string            `protobuf:"bytes,3,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	TaskType        string            `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Goal            string            `protobuf:"bytes,5,opt,name=goal,proto3" json:"goal,omitempty"`
	ContextRef      string            `protobuf:"bytes,6,opt,name=context_ref,json=contextRef,proto3" json:"context_ref,omitempty"`
	StartTs         uint64            `protobuf:"varint,7,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs           uint64            `protobuf:"varint,8,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	State           SessionState      `protobuf:"varint,9,opt,name=state,proto3,enum=agent.proto.SessionState" json:"state,omitempty"`
	BudgetToken     int64             `protobuf:"varint,10,opt,name=budget_token,json=budgetToken,proto3" json:"budget_token,omitempty"`
	BudgetTimeMs    int64             `protobuf:"varint,11,opt,name=budget_time_ms,json=budgetTimeMs,proto3" json:"budget_time_ms,omitempty"`
	Metadata        map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
}

func (x *SessionInfo) String() string {
	return "SessionInfo"
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SessionInfo) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *SessionInfo) GetParentSessionID() string {
	if x != nil {
		return x.ParentSessionID
	}
	return ""
}

func (x *SessionInfo) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *SessionInfo) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *SessionInfo) GetContextRef() string {
	if x != nil {
		return x.ContextRef
	}
	return ""
}

func (x *SessionInfo) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *SessionInfo) GetEndTs() uint64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *SessionInfo) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SESSION_UNKNOWN
}

func (x *SessionInfo) GetBudgetToken() int64 {
	if x != nil {
		return x.BudgetToken
	}
	return 0
}

func (x *SessionInfo) GetBudgetTimeMs() int64 {
	if x != nil {
		return x.BudgetTimeMs
	}
	return 0
}

func (x *SessionInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateAgentRequest 创建Agent请求
type CreateAgentRequest struct {
	TenantID            string            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceID         string            `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentType           string            `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	RoleProfile         string            `protobuf:"bytes,4,opt,name=role_profile,json=roleProfile,proto3" json:"role_profile,omitempty"`
	CapabilitySet       []string          `protobuf:"bytes,5,rep,name=capability_set,json=capabilitySet,proto3" json:"capability_set,omitempty"`
	DefaultMemoryPolicy string            `protobuf:"bytes,6,opt,name=default_memory_policy,json=defaultMemoryPolicy,proto3" json:"default_memory_policy,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
}

func (x *CreateAgentRequest) String() string {
	return "CreateAgentRequest"
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *CreateAgentRequest) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

func (x *CreateAgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *CreateAgentRequest) GetRoleProfile() string {
	if x != nil {
		return x.RoleProfile
	}
	return ""
}

func (x *CreateAgentRequest) GetCapabilitySet() []string {
	if x != nil {
		return x.CapabilitySet
	}
	return nil
}

func (x *CreateAgentRequest) GetDefaultMemoryPolicy() string {
	if x != nil {
		return x.DefaultMemoryPolicy
	}
	return ""
}

func (x *CreateAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateAgentResponse 创建Agent响应
type CreateAgentResponse struct {
	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentID string           `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
}

func (x *CreateAgentResponse) String() string {
	return "CreateAgentResponse"
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateAgentResponse) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

// GetAgentRequest 获取Agent请求
type GetAgentRequest struct {
	AgentID string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
}

func (x *GetAgentRequest) String() string {
	return "GetAgentRequest"
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

// GetAgentResponse 获取Agent响应
type GetAgentResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Agent  *AgentInfo       `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
}

func (x *GetAgentResponse) String() string {
	return "GetAgentResponse"
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

// ListAgentsRequest 列出Agent请求
type ListAgentsRequest struct {
	TenantID    string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceID string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AgentType   string `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
}

func (x *ListAgentsRequest) String() string {
	return "ListAgentsRequest"
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *ListAgentsRequest) GetWorkspaceID() string {
	if x != nil {
		return x.WorkspaceID
	}
	return ""
}

func (x *ListAgentsRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

// ListAgentsResponse 列出Agent响应
type ListAgentsResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Agents []*AgentInfo     `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
}

func (x *ListAgentsResponse) String() string {
	return "ListAgentsResponse"
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// UpdateAgentRequest 更新Agent请求
type UpdateAgentRequest struct {
	AgentID       string            `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RoleProfile   string            `protobuf:"bytes,2,opt,name=role_profile,json=roleProfile,proto3" json:"role_profile,omitempty"`
	CapabilitySet []string          `protobuf:"bytes,3,rep,name=capability_set,json=capabilitySet,proto3" json:"capability_set,omitempty"`
	PolicyRef     string            `protobuf:"bytes,4,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
}

func (x *UpdateAgentRequest) String() string {
	return "UpdateAgentRequest"
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *UpdateAgentRequest) GetRoleProfile() string {
	if x != nil {
		return x.RoleProfile
	}
	return ""
}

func (x *UpdateAgentRequest) GetCapabilitySet() []string {
	if x != nil {
		return x.CapabilitySet
	}
	return nil
}

func (x *UpdateAgentRequest) GetPolicyRef() string {
	if x != nil {
		return x.PolicyRef
	}
	return ""
}

func (x *UpdateAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateAgentResponse 更新Agent响应
type UpdateAgentResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateAgentResponse) Reset() {
	*x = UpdateAgentResponse{}
}

func (x *UpdateAgentResponse) String() string {
	return "UpdateAgentResponse"
}

func (*UpdateAgentResponse) ProtoMessage() {}

func (x *UpdateAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeleteAgentRequest 删除Agent请求
type DeleteAgentRequest struct {
	AgentID string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
}

func (x *DeleteAgentRequest) String() string {
	return "DeleteAgentRequest"
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

// DeleteAgentResponse 删除Agent响应
type DeleteAgentResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
}

func (x *DeleteAgentResponse) String() string {
	return "DeleteAgentResponse"
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// CreateSessionRequest 创建Session请求
type CreateSessionRequest struct {
	AgentID         string            `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentSessionID string            `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	TaskType        string            `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Goal            string            `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	ContextRef      string            `protobuf:"bytes,5,opt,name=context_ref,json=contextRef,proto3" json:"context_ref,omitempty"`
	BudgetToken     int64             `protobuf:"varint,6,opt,name=budget_token,json=budgetToken,proto3" json:"budget_token,omitempty"`
	BudgetTimeMs    int64             `protobuf:"varint,7,opt,name=budget_time_ms,json=budgetTimeMs,proto3" json:"budget_time_ms,omitempty"`
	Metadata        map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
}

func (x *CreateSessionRequest) String() string {
	return "CreateSessionRequest"
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *CreateSessionRequest) GetParentSessionID() string {
	if x != nil {
		return x.ParentSessionID
	}
	return ""
}

func (x *CreateSessionRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateSessionRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateSessionRequest) GetContextRef() string {
	if x != nil {
		return x.ContextRef
	}
	return ""
}

func (x *CreateSessionRequest) GetBudgetToken() int64 {
	if x != nil {
		return x.BudgetToken
	}
	return 0
}

func (x *CreateSessionRequest) GetBudgetTimeMs() int64 {
	if x != nil {
		return x.BudgetTimeMs
	}
	return 0
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateSessionResponse 创建Session响应
type CreateSessionResponse struct {
	Status    *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SessionID string           `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
}

func (x *CreateSessionResponse) String() string {
	return "CreateSessionResponse"
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateSessionResponse) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

// GetSessionRequest 获取Session请求
type GetSessionRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
}

func (x *GetSessionRequest) String() string {
	return "GetSessionRequest"
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

// GetSessionResponse 获取Session响应
type GetSessionResponse struct {
	Status  *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Session *SessionInfo     `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
}

func (x *GetSessionResponse) String() string {
	return "GetSessionResponse"
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

// ListSessionsRequest 列出Session请求
type ListSessionsRequest struct {
	AgentID         string       `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentSessionID string       `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	State           SessionState `protobuf:"varint,3,opt,name=state,proto3,enum=agent.proto.SessionState" json:"state,omitempty"`
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
}

func (x *ListSessionsRequest) String() string {
	return "ListSessionsRequest"
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *ListSessionsRequest) GetParentSessionID() string {
	if x != nil {
		return x.ParentSessionID
	}
	return ""
}

func (x *ListSessionsRequest) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SESSION_UNKNOWN
}

// ListSessionsResponse 列出Session响应
type ListSessionsResponse struct {
	Status   *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Sessions []*SessionInfo   `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
}

func (x *ListSessionsResponse) String() string {
	return "ListSessionsResponse"
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// UpdateSessionRequest 更新Session请求
type UpdateSessionRequest struct {
	SessionID string       `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State     SessionState `protobuf:"varint,2,opt,name=state,proto3,enum=agent.proto.SessionState" json:"state,omitempty"`
	Goal      string       `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
}

func (x *UpdateSessionRequest) String() string {
	return "UpdateSessionRequest"
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *UpdateSessionRequest) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SESSION_UNKNOWN
}

func (x *UpdateSessionRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *UpdateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateSessionResponse 更新Session响应
type UpdateSessionResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
}

func (x *UpdateSessionResponse) String() string {
	return "UpdateSessionResponse"
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) GetStatus() *commonpb.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// AgentServiceClient is the client API for AgentService service.
type AgentServiceClient interface {
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error)
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/GetAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/ListAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error) {
	out := new(UpdateAgentResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/UpdateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error) {
	out := new(DeleteAgentResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/GetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/ListSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, "/agent.proto.AgentService/UpdateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error)
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}

func (UnimplementedAgentServiceServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}

func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}

func (UnimplementedAgentServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}

func (UnimplementedAgentServiceServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}

func (UnimplementedAgentServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}

func (UnimplementedAgentServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}

func (UnimplementedAgentServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}

func (UnimplementedAgentServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}

// RegisterAgentServiceServer registers the AgentServiceServer to the grpc.Server.
func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/GetAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/ListAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/UpdateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/ListSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.proto.AgentService/UpdateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.proto.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentService_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentService_DeleteAgent_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AgentService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _AgentService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentService_ListSessions_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _AgentService_UpdateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
